### ISSUE TITLE
Failed to download content, too many users have downloaded

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#1180]
It seems we are reaching the limit of downloads that we can do from Google Drive.

![image](https://user-images.githubusercontent.com/4332953/51802479-ecf64e80-224a-11e9-8cf0-dd988da425d6.png)

It's affecting all the files in our Google Drive, including older versions and releases.

**Comment by quanheng123** [comment]
Hi, just met this problem when re-set up, but what I'm now using the assets in 0.8.2, where can I find a alternative link to download? 
Thanks!

**Comment by nsubiron** [comment]
I'm afraid we don't have any other link available.

**Comment by mrwesleycrusher** [comment]
Would this be why when Update.sh downloads Content.tar.gz it actually fetches a "HTML document, ASCII text, with very long lines" ?

**Comment by nsubiron** [comment]
Seems to be fixed for now

**Comment by shivnetra1411** [comment]
While running ./Update.sh getting this error. 

Backing up existing Content...
'/home/kpit/carla/Unreal/CarlaUE4/Content/Carla' -> '/home/kpit/carla/Unreal/CarlaUE4/Content/Carla_20190129125907'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 555, in urlopen
    self._prepare_proxy(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 753, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 252, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 305, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 589, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Util/download_from_gdrive.py", line 82, in <module>
    download_file_from_google_drive(args.id, args.destination)
  File "./Util/download_from_gdrive.py", line 59, in download_file_from_google_drive
    response = session.get(url, params={'id': id}, stream=True)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 492, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

**Comment by xmba15** [comment]
Hi, I am trying to use ./carla/Update.sh now and it seems like the links are not downloadable now. What is the alternative way to build carla then?

**Comment by xmba15** [comment]
Seems like the contents are reachable with 
```
git lfs clone https://bitbucket.org/carla-simulator/carla-content Unreal/CarlaUE4/Content/Carla
```
If that is the case, is it better to only use git lfs inside Update.sh instead of downloading from google drive?
