### ISSUE TITLE
RuntimeError: cannot import "carla_server_pb2.py", run the protobuf compiler to generate this file

### ISSUE THREAD

**Issue by tdam2112** [carla-simulator/carla#1330]
Hello, I'm currently trying to test CARLA in server-client mode for the first time with python 3.6 and I get the following error when i try to run the python script:

C:\Coursera\CarlaSimulator\PythonClient>python manual_control.py
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Coursera\CarlaSimulator\PythonClient\carla\transform.py", line 18, in <module>
    from . import carla_server_pb2 as carla_protocol
  File "C:\Coursera\CarlaSimulator\PythonClient\carla\carla_server_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\tdam2\AppData\Roaming\Python\Python36\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manual_control.py", line 58, in <module>
    from carla import image_converter
  File "C:\Coursera\CarlaSimulator\PythonClient\carla\image_converter.py", line 25, in <module>
    from . import sensor
  File "C:\Coursera\CarlaSimulator\PythonClient\carla\sensor.py", line 19, in <module>
    from .transform import Transform, Translation, Rotation, Scale
  File "C:\Coursera\CarlaSimulator\PythonClient\carla\transform.py", line 20, in <module>
    raise RuntimeError('cannot import "carla_server_pb2.py", run '
RuntimeError: cannot import "carla_server_pb2.py", run the protobuf compiler to generate this file

I've navigated through some throubleshooting,
1. although I have anaconda installed with python 3.7 I'm sure I have all the dependencies installed in python 3.6 and I've uninstalled some of them from Anaconda to see if it would solve but it did not.

2. I've uninstalled and reistalled protobuf in case it was corrupt with no alteration in the RuntimeError

I'm following the following guide to install and setup CARLA: Coursera CARLA Setup for Windows. I've attached it below, I've followed the guide successfully up to this point, I'm not able to connect my python client to the idling window running the CARLA simulator.

guide:
[IFfxQie8Eem9HA6xGGaRfg_20f6060027bc11e98ed3dfcfdba7c72b_CARLA-Setup-Guide-_Windows-x64_.pdf](https://github.com/carla-simulator/carla/files/2922649/IFfxQie8Eem9HA6xGGaRfg_20f6060027bc11e98ed3dfcfdba7c72b_CARLA-Setup-Guide-_Windows-x64_.pdf)

Does anyone know anything I could try to make this work?

**Comment by tdam2112** [comment]
Managed to make it work by un installing python 3.6 ad going with python 3.5 instead
