### ISSUE TITLE
[0.9.4] Windows compiled version "DLL load failed"

### ISSUE THREAD

**Issue by Atlunch** [carla-simulator/carla#1548]
Hello everyone, 

i just downloaded the windows compiled version 0.9.4 and tried to use the "manuel_control.py".
I looks like that there is still a problem with the DLL import.

______________________________________________________________________
Traceback (most recent call last):
  File "manual_control.py", line 70, in <module>
    import carla
  File "PythonAPI\carla-0.9.4-py3.7-win-amd64.egg\carla\__init__.py", line 7, in <module>
  File "PythonAPI\carla-0.9.4-py3.7-win-amd64.egg\carla\libcarla.py", line 7, in <module>
  File "PythonAPI\carla-0.9.4-py3.7-win-amd64.egg\carla\libcarla.py", line 6, in __bootstrap__
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
_______________________________________________________________________

My system:
Windows 10
Python 3.7

_______________________________________________________________________

In #1345  is referenced, that in #1401 the bug was fixed. 
But the compiled version includes still the old code.
Where is the newest windows branch?

or

Can someone over a instruction what i have to change inside the compiled version?

Best regards
Atlunch

**Comment by Atlunch** [comment]
I could solved it by switching to Anaconda3 64 Bit and changing the font like in #1475 mentioned.

I hade problems installing pygame for Anaconda3 using  "conda install -c cogsci pygame", so i just installed pygame using "pip install pygame" directly inside the "Anaconda Prompt"

`
Wrong: Line 372:  fonts = [x for x in pygame.font.get_fonts() if 'mono' in x]

Correct: Line 372:  fonts = [x for x in pygame.font.get_fonts() if 'arial' in x] 

`
