### ISSUE TITLE
"OSError: [WinError 193] %1 is not a valid Win32 application" when running manual_control.py

### ISSUE THREAD

**Issue by KC900201** [carla-simulator/carla#1970]
I am running CARLA version 0.9.5 on my Windows PC with 64-bit Windows 10 version. I've installed 64-bit version Python 3.7.4 on my PC to run the CARLA simulator with pygame (1.9.6 version) and numpy pre-installed. Whenever I try to run the script manual_control.py on the terminal, the error below occurs:

Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "manual_control.py", line 118, in <module>
    import numpy as np
  File "C:\Users\atsumilab\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\atsumilab\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py", line 23, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\atsumilab\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

![error](https://user-images.githubusercontent.com/46585072/62448914-dace0d80-b7a3-11e9-9e36-b20dc75dc555.PNG)

Kindly suggest any solution to solve the issue. If there's any missing information, please reply in the thread so that I can provide ASAP

**Comment by KC900201** [comment]
Hi all,

The error is fixed after I upgrade the numpy version to numpy-1.17.0 using command line "pip install --user upgrade numpy". So far, I've managed to run the script using pygame version 1.9.6 and numpy version 1.17.0. Hope this thread can be a reference.
