### ISSUE TITLE
a threading.py issue of 0.9.5 Python Client

### ISSUE THREAD

**Issue by noahcao** [carla-simulator/carla#1990]
I used to work on 0.9.4 and my code works well. After migrating to 0.9.4 (change the simulator and no other modification of code), a thread issue occurs. I use the 0.9.5 api installed by pip.

```
Exception ignored in: <module 'threading' from '/home/jinkun/anaconda3/envs/py3.5_carla95/lib/python3.5/threading.py'>
Traceback (most recent call last):
File "/home/jinkun/anaconda3/envs/py3.5_carla95/lib/python3.5/threading.py", line 1304, in _shutdown
       _main_thread._delete()
File "/home/jinkun/anaconda3/envs/py3.5_carla95/lib/python3.5/threading.py", line 1013, in _delete
       del _active[get_ident()]
KeyError: 140285862450944
```

I found few issues about such an error online. Because all carla api are packaged in C++ not in python files. I also have no idea how to quickly find the error source.

**Comment by noahcao** [comment]
I use carla 0.9.5 because it can provide the lane type of a waypoint to help me check whether the vehicle is offroad. Is there any other way to realize it on 0.9.4?
