### ISSUE TITLE
Error: No module named "scene_layout" when running scenario_runner.py

### ISSUE THREAD

**Issue by Jack-Pinnington** [carla-simulator/carla#2259]
Hello!

I'm trying to use the scenario_runner.py script as mentioned in this Getting Started tutorial: "https://github.com/carla-simulator/scenario_runner/blob/master/Docs/getting_started.md". When I call the code "python scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld" from the Command line I read the following error:

Traceback (most recent call last):
  File "scenario_runner.py", line 42, in <module>
    from srunner.challenge.autoagents.agent_wrapper import SensorConfigurationInvalid
  File "/vol/teaching/drive_weather/scenario_runner/srunner/challenge/autoagents/agent_wrapper.py", line 18, in <module>
    from srunner.challenge.envs.scene_layout_sensors import SceneLayoutReader, ObjectFinder
  File "/vol/teaching/drive_weather/scenario_runner/srunner/challenge/envs/scene_layout_sensors.py", line 6, in <module>
    import scene_layout as scene_layout_parser  # This should come from CARLA path
ImportError: No module named scene_layout

I've run Carla with the Python API successfully before (import carla works fine and I can run my own scripts which are changing the weather and handling actors) and I can see the egg file in my PYTHONPATH: /<path>/PythonAPI/carla/dist/carla-0.9.6-py2.7-linux-x86_64.egg

What do I need to add to my environment to get this to run? Using Python 2.7.15.

Any help greatly appreciated!

Jack

**Comment by Jack-Pinnington** [comment]
Hello,

I've found the solution to this issue. 
The PYTHONPATH in my bash environment needed to be updated to include the /PythonAPI/carla directory where scene_layout.py is stored.

I added the following line to my .bashrc:
PYTHONPATH=$PYTHONPATH:<dir>/PythonAPI/carla

Where <dir> is the full path to PythonAPI.

Thanks,
Jack
