### ISSUE TITLE
Unable to read sensor data when the simulator is built from souces.

### ISSUE THREAD

**Issue by YashBansod** [carla-simulator/carla#259]
I built carla from sources and packaged it for Linux. Now I run the packaged simulator in server mode.
But, I am unable to get any sensor data in the manual_control.py code. I debugged an found that the measurements are there but the sensor data isn't.
I made no changes to the manual_control.py in the Python Client or the Town01 and Town02 of the carla project in UE4.

The error I am getting is:

> Traceback (most recent call last):
>   File "/snap/pycharm-professional/47/helpers/pydev/pydevd.py", line 1668, in <module>
>     main()
>   File "/snap/pycharm-professional/47/helpers/pydev/pydevd.py", line 1662, in main
>     globals = debugger.run(setup['file'], None, None, is_module)
>   File "/snap/pycharm-professional/47/helpers/pydev/pydevd.py", line 1072, in run
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "/home/uidk4283/PycharmProjects/CARLA_Client/manual_control.py", line 375, in <module>
>     main()
>   File "/home/uidk4283/PycharmProjects/CARLA_Client/manual_control.py", line 364, in main
>     game.execute()
>   File "/home/uidk4283/PycharmProjects/CARLA_Client/manual_control.py", line 145, in execute
>     self._on_loop()
>   File "/home/uidk4283/PycharmProjects/CARLA_Client/manual_control.py", line 177, in _on_loop
>     self._main_image = sensor_data['CameraRGB']
> KeyError: 'CameraRGB'

Also, If I remove all the sensors from the configuration and just run the game in autopilot mode, it runs, but only the sensor data is missing.

**Comment by YashBansod** [comment]
I was able to resolve this issue myself. 
The error was happening because the simulator was packaged using the latest CARLA source code where the configuration of the sensor suite has changed.
Just copying the Python Client folder from the source code to the one available along with the pre-compiled binaries solved the problem.
