### ISSUE TITLE
Segfault when loading large OpenDRIVE map

### ISSUE THREAD

**Issue by dsche** [carla-simulator/carla#3052]
I am experiencing a segmentation fault on loading of a large (~38M) OpenDRIVE map via the Python API. The segfault seems to happen somewhere in the string conversion on RPC call, even before the string is being meaningfully parsed, let alone a map constructed:

```
Thread 1 "CarlaUE4-Linux-" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:384
384     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:384
#1  0x0000000001e8728a in FGenericPlatformString::Convert<char16_t, char16_t> (Dest=0x7fff658b0000 u"", 
    Src=<optimized out>, BogusChar=63 u'?', DestSize=<optimized out>, SrcSize=<optimized out>)
    at Runtime/Core/Public/GenericPlatform/GenericPlatformString.h:126
#2  FString::FString<char16_t, void> (this=<optimized out>, 
    InSrc=0x7fffc69a0000 u"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<OpenDRIVE>\n    <header revMajor=\"1\" revMinor=\"4\" name=\"\" version=\"1.00\" date=\"Mon May 25 11:04:31 2020\" north=\"3642.90\" south=\"0.00\" east=\"3629.47\" west=\"0.00\"/"..., InCount=<optimized out>) at Runtime/Core/Public/Containers/UnrealString.h:141
#3  carla::rpc::ToLongFString (str=...)
    at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/carla/rpc/String.h:54
#4  0x0000000001ee4866 in FCarlaServer::FPimpl::BindActions()::$_26::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, carla::rpc::OpendriveGenerationParameters) const (
    this=<optimized out>, opendrive=..., Params=...)
    at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp:242
#5  carla::rpc::detail::FunctionWrapper<carla::rpc::Response<void> (*)(std::__1::basic_string<char, std::__1::char_t--Type <RET> for more, q to quit, c to continue without paging--c
raits<char>, std::__1::allocator<char> > const&, carla::rpc::OpendriveGenerationParameters)>::WrapSyncCall<FCarlaServer::FPimpl::BindActions()::$_26&>(boost::asio::io_context&, FCarlaServer::FPimpl::BindActions()::$_26&)::{lambda(carla::rpc::Metadata, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, carla::rpc::OpendriveGenerationParameters)#1}::operator()(carla::rpc::Metadata, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, carla::rpc::OpendriveGenerationParameters) const::{lambda()#1}::operator()() const (this=<optimized out>) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/carla/rpc/Server.h:106
#6  std::__1::__invoke<carla::rpc::detail::FunctionWrapper<carla::rpc::Response<void> (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, carla::rpc::OpendriveGenerationParameters)>::WrapSyncCall<FCarlaServer::FPimpl::BindActions()::$_26&>(boost::asio::io_context&, FCarlaServer::FPimpl::BindActions()::$_26&)::{lambda(carla::rpc::Metadata, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, carla::rpc::OpendriveGenerationParameters)#1}::operator()(carla::rpc::Metadata, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, carla::rpc::OpendriveGenerationParameters) const::{lambda()#1}&> (__f=...) at ThirdParty/Linux/LibCxx/include/c++/v1/type_traits:4353
#7  std::__1::__packaged_task_func<carla::rpc::detail::FunctionWrapper<carla::rpc::Response<void> (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, carla::rpc::OpendriveGenerationParameters)>::WrapSyncCall<FCarlaServer::FPimpl::BindActions()::$_26&>(boost::asio::io_context&, FCarlaServer::FPimpl::BindActions()::$_26&)::{lambda(carla::rpc::Metadata, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, carla::rpc::OpendriveGenerationParameters)#1}::operator()(carla::rpc::Metadata, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, carla::rpc::OpendriveGenerationParameters) const::{lambda()#1}, std::__1::allocator<{lambda(carla::rpc::Metadata, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, carla::rpc::OpendriveGenerationParameters)#1}>, carla::rpc::Response<void> ()>::operator()() (this=<optimized out>) at ThirdParty/Linux/LibCxx/include/c++/v1/future:1821
#8  0x0000000001ee3772 in std::__1::__packaged_task_function<carla::rpc::Response<void> ()>::operator()() const (this=0x7fffffffda90) at ThirdParty/Linux/LibCxx/include/c++/v1/future:1998
#9  std::__1::packaged_task<carla::rpc::Response<void> ()>::operator()() (this=0x7fffffffda90) at ThirdParty/Linux/LibCxx/include/c++/v1/future:2089
#10 0x0000000001ee3668 in boost::asio::asio_handler_invoke<carla::detail::MoveWrapper<std::__1::packaged_task<carla::rpc::Response<void> ()> > >(carla::detail::MoveWrapper<std::__1::packaged_task<carla::rpc::Response<void> ()> >&, ...) (function=...) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/boost/asio/handler_invoke_hook.hpp:69
#11 boost_asio_handler_invoke_helpers::invoke<carla::detail::MoveWrapper<std::__1::packaged_task<carla::rpc::Response<void> ()> >, carla::detail::MoveWrapper<std::__1::packaged_task<carla::rpc::Response<void> ()> > >(carla::detail::MoveWrapper<std::__1::packaged_task<carla::rpc::Response<void> ()> >&, carla::detail::MoveWrapper<std::__1::packaged_task<carla::rpc::Response<void> ()> >&) (function=..., context=...) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#12 boost::asio::detail::handler_work<carla::detail::MoveWrapper<std::__1::packaged_task<carla::rpc::Response<void> ()> >, boost::asio::system_executor, boost::asio::system_executor>::complete<carla::detail::MoveWrapper<std::__1::packaged_task<carla::rpc::Response<void> ()> > >(carla::detail::MoveWrapper<std::__1::packaged_task<carla::rpc::Response<void> ()> >&, carla::detail::MoveWrapper<std::__1::packaged_task<carla::rpc::Response<void> ()> >&) (this=<optimized out>, function=..., handler=...) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/boost/asio/detail/handler_work.hpp:100
#13 boost::asio::detail::completion_handler<carla::detail::MoveWrapper<std::__1::packaged_task<carla::rpc::Response<void> ()> > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (owner=0x7fffb2c6d100, base=0x7fff47712c40) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/boost/asio/detail/completion_handler.hpp:70
#14 0x0000000001f1d8c0 in boost::asio::detail::scheduler_operation::complete (this=<optimized out>, owner=0x7fffb2c6d100, ec=..., bytes_transferred=<optimized out>) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/boost/asio/detail/scheduler_operation.hpp:40
#15 boost::asio::detail::scheduler::do_wait_one (this=0x7fffb2c6d100, lock=..., this_thread=..., usec=<optimized out>, ec=...) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/boost/asio/detail/impl/scheduler.ipp:527
#16 0x0000000001f1d2a1 in boost::asio::detail::scheduler::wait_one (this=0x7fffb2c6d100, usec=9999, ec=...) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/boost/asio/detail/impl/scheduler.ipp:239
#17 0x0000000001f1d10e in boost::asio::io_context::run_one_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > (this=0x7fff42bc36d8, abs_time=...) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/boost/asio/impl/io_context.hpp:115
#18 0x0000000001e841fb in boost::asio::io_context::run_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > (this=<optimized out>, abs_time=...) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/boost/asio/impl/io_context.hpp:90
#19 boost::asio::io_context::run_for<long long, std::__1::ratio<1l, 1000l> > (this=<optimized out>, rel_time=...) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/boost/asio/impl/io_context.hpp:82
#20 carla::rpc::Server::SyncRunFor (this=<optimized out>, duration=...) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/CarlaDependencies/include/carla/rpc/Server.h:54
#21 FCarlaServer::RunSome (this=0x7fffb1ad2b78, Milliseconds=10) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp:1169
#22 FCarlaEngine::OnPostTick (this=0x7fffb1ad2b70) at /home/jenkins/workspace/carla_master/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEngine.cpp:120
#23 0x0000000001f2e05f in TMemberFunctionCaller<FCarlaEngine, void (FCarlaEngine::*)(UWorld*, ELevelTick, float)>::operator()<UWorld*&, ELevelTick&, float&> (this=<optimized out>, Args=<optimized out>, Args=<optimized out>, Args=<optimized out>) at Runtime/Core/Public/Delegates/DelegateInstanceInterface.h:156
#24 UE4Tuple_Private::TTupleImpl<TIntegerSequence<unsigned int>>::ApplyAfter<TMemberFunctionCaller<FCarlaEngine, void (FCarlaEngine::*)(UWorld*, ELevelTick, float)>, UWorld*&, ELevelTick&, float&>(TMemberFunctionCaller<FCarlaEngine, void (FCarlaEngine::*)(UWorld*, ELevelTick, float)>&&, UWorld*&, ELevelTick&, float&) const (this=<optimized out>, Func=..., Args=<optimized out>, Args=<optimized out>, Args=<optimized out>) at Runtime/Core/Public/Templates/Tuple.h:285
#25 TBaseRawMethodDelegateInstance<false, FCarlaEngine, TTypeWrapper<void> (UWorld*, ELevelTick, float)>::Execute(UWorld*, ELevelTick, float) const (this=<optimized out>, Params=0, Params=0, Params=0) at Runtime/Core/Public/Delegates/DelegateInstancesImpl.h:481
#26 TBaseRawMethodDelegateInstance<false, FCarlaEngine, void (UWorld*, ELevelTick, float)>::ExecuteIfSafe(UWorld*, ELevelTick, float) const (this=<optimized out>, Params=0, Params=0, Params=0) at Runtime/Core/Public/Delegates/DelegateInstancesImpl.h:539
#27 0x000000000385399a in TBaseMulticastDelegate<void, UWorld*, ELevelTick, float>::Broadcast (this=0x5236868 <FWorldDelegates::OnWorldPostActorTick>, Params=0.0118845906, Params=0.0118845906, Params=0.0118845906) at Runtime/Core/Public/Delegates/DelegateSignatureImpl.inl:1013
#28 0x0000000003853351 in UWorld::Tick (this=<optimized out>, TickType=LEVELTICK_All, DeltaSeconds=0.0118845906) at Runtime/Engine/Private/LevelTick.cpp:1684
#29 0x000000000375fce9 in UGameEngine::Tick (this=0x7fffd36f0100, DeltaSeconds=<optimized out>, bIdleMode=<optimized out>) at Runtime/Engine/Private/GameEngine.cpp:1665
#30 0x0000000001e50e8e in FEngineLoop::Tick (this=0x50303b0 <GEngineLoop>) at Runtime/Launch/Private/LaunchEngineLoop.cpp:4479
#31 0x0000000001e5220a in EngineTick () at Runtime/Launch/Private/Launch.cpp:62
#32 GuardedMain (CmdLine=<optimized out>) at Runtime/Launch/Private/Launch.cpp:175
#33 0x0000000003f21828 in CommonUnixMain (argc=<optimized out>, argv=0x7fffffffe2e8, RealMain=0x1e51fc0 <GuardedMain(char16_t const*)>, AppExitCallback=0x1e5b310 <LaunchUnix_FEngineLoop_AppExit()>) at Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:264
#34 0x00007ffff76b80b3 in __libc_start_main (main=0x1e5b300 <main(int, char**)>, argc=2, argv=0x7fffffffe2e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe2d8) at ../csu/libc-start.c:308
#35 0x0000000001e4f029 in _start ()
```

[map.xodr.zip](https://github.com/carla-simulator/carla/files/4912609/map.xodr.zip)

**Comment by germanros1987** [comment]
@marcgpuig could you take a look?
