### ISSUE TITLE
CARLA SUMO Co-Simulation, FileNotFoundError: [Errno 2] No such file or directory: 'sumo-gui': 'sumo-gui'

### ISSUE THREAD

**Issue by philippwulff** [carla-simulator/carla#3501]
I installed CARLA with [these](https://carla.readthedocs.io/en/latest/build_linux/) instructions on Linux Mint 18.3

And I installed SUMO from [here](https://sumo.dlr.de/docs/Installing/Linux_Build.html), since the installation from source was recommended.

I also set the environment variable for `SUMO_HOME` and can open the `sumo-gui` via typing it into the terminal.

When trying to run the co-simulation with `python3 run_synchronization.py examples/Town03.sumocfg --sumo-gui`, I receive this error:

```
INFO: Starting new sumo server...
INFO: Remember to press the play button to start the simulation
Traceback (most recent call last):
  File "run_synchronization.py", line 316, in <module>
    synchronization_loop(arguments)
  File "run_synchronization.py", line 234, in synchronization_loop
    args.sumo_port, args.sumo_gui, args.client_order)
  File "/home/philipp/carla/Co-Simulation/Sumo/sumo_integration/sumo_simulation.py", line 326, in __init__
    '--collision.check-junctions'
  File "/home/philipp/.local/lib/python3.6/site-packages/traci/main.py", line 130, in start
    sumoProcess = subprocess.Popen(cmd2)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sumo-gui': 'sumo-gui'
```

I found a similar issue [5000](https://github.com/eclipse/sumo/issues/5000) in the SUMO repo, but the solution does not help me. Also, I think the environment variable cannot be the issue, since I can open `sumo-gui`.

**Comment by philippwulff** [comment]
When I run `echo $SUMO_HOME` in the terminal, I get

/sumo/bin:~/sumo/bin:/home/philipp/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

and ~/sumo is the root folder for the sumo installation

And it looks like CARLA wants to open sumo-gui from the root folder of the SUMO installation.

So I added the line `export SUMO_HOME=~/sumo` to my .bashrc file, which resolves the issue.
