### ISSUE TITLE
Getting errors while trying to run PythonAPI/examples/lidar_to_camera.py

### ISSUE THREAD

**Issue by aczy118** [carla-simulator/carla#3691]
Hi there,
 When I try to run the above script shared by marcgpuig/lidar_to_camera I am getting the error below:

C:\Users\WindowsNoEditor\PythonAPI\examples>python lidar_to_camera.py
(0/500) Simulation: 3387 Camera: 3387 Lidar: 3387 Traceback (most recent call last):
  File "lidar_to_camera.py", line 352, in <module>
    main()
  File " lidar_to_camera.py", line 344, in main
    tutorial(args)
  File " lidar_to_camera.py", line 161, in tutorial
    p_cloud = np.reshape(p_cloud, (p_cloud_size, 4))
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 279, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 92262 into shape (30754,4)

I am changing this line **"p_cloud = np.reshape(p_cloud, (p_cloud_size, 4))"**
 to **"p_cloud = np.reshape(p_cloud, (p_cloud_size, 3))"**

Then getting this error:
C:\Users\WindowsNoEditor\PythonAPI\examples>python  lidar_to_camera.py
(0/500) Simulation: 40271 Camera: 40271 Lidar: 40271 Traceback (most recent call last):
  File "lidar_to_camera.py", line 352, in <module>
    main()
  File "lidar_to_camera.py", line 344, in main
    tutorial(args)
  File "lidar_to_camera.py", line 165, in tutorial
    intensity = np.array(p_cloud[:, 3])
IndexError: index 3 is out of bounds for axis 1 with size 3

and changing  this line **"intensity = np.array(p_cloud[:, 3])"** to **"intensity = np.array(p_cloud[:, 2])"**. But this time I am getting this error:

C:\Users\WindowsNoEditor\PythonAPI\examples>python  lidar_to_camera.py
(0/500) Simulation: 46658 Camera: 46658 Lidar: 46658 Traceback (most recent call last):
  File " lidar_to_camera.py", line 352, in <module>
    main()
  File " lidar_to_camera.py", line 344, in main
    tutorial(args)
  File " lidar_to_camera.py", line 176, in tutorial
    lidar_2_world = lidar.get_transform().get_matrix()
AttributeError: 'Transform' object has no attribute 'get_matrix'

It seems a simple error but I am a newbie. It would be appreciated if you could help me.

**Comment by aczy118** [comment]
The problem is I was trying to run the script with an older version. It works fine with the latest one.
