### ISSUE TITLE
Error while running PythonAPI/examples/lidar_to_camera.py

### ISSUE THREAD

**Issue by curio-code** [carla-simulator/carla#3773]
While running lidar_to_camera.py script I am facing the following issue

`~/carla/PythonAPI/examples$ python3 lidar_to_camera.py`
`(0/500) Simulation: 300204 Camera: 300204 Lidar: 300204 Traceback (most recent call last):`
`  File "lidar_to_camera.py", line 352, in <module>`
`    main()`
`  File "lidar_to_camera.py", line 344, in main`
`    tutorial(args)`
`  File "lidar_to_camera.py", line 258, in tutorial`
`    image.save("_out/%08d.png" % image_data.frame)`
`  File "/home//.local/lib/python3.7/site-packages/PIL/Image.py", line 2161, in save`
`    fp = builtins.open(filename, "w+b")`
`FileNotFoundError: [Errno 2] No such file or directory: '_out/00300204.png'`

**Comment by curio-code** [comment]
Just have to make a folder named '_out'
