### ISSUE TITLE
tensor flow issue

### ISSUE THREAD

**Issue by Fady-Maged-Louis** [carla-simulator/carla#4270]
when i try to run carla code that have tensorflow that error appers
```
***************************************************************
Failed to import TensorFlow. Please note that TensorFlow is not installed by default when you install TFDS. This allow you to choose to install either `tf-nightly` or `tensorflow`. Please install the most recent version of TensorFlow, by following instructions at https://tensorflow.org/install.
***************************************************************


Traceback (most recent call last):
  File "exscel2.py", line 22, in <module>
    import tensorflow as tf
  File "C:\carla2\PythonAPI\examples\tensorflow.py", line 1, in <module>
    import tensorflow_datasets as tfds
  File "C:\Users\fadym\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\__init__.py", line 43, in <module>
    from tensorflow_datasets.core import tf_compat
  File "C:\Users\fadym\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\__init__.py", line 21, in <module>
    tf_compat.ensure_tf_install()
  File "C:\Users\fadym\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\tf_compat.py", line 47, in ensure_tf_install
    import tensorflow.compat.v2 as tf  # pylint: disable=import-outside-toplevel
ModuleNotFoundError: No module named 'tensorflow.compat'; 'tensorflow' is not a package
```

**Comment by corkyw10** [comment]
This looks like it's a tensorflow related question, not CARLA. Maybe [stackoverflow](https://stackoverflow.com/) is a better option for you to ask your question? If you feel like it's related to CARLA, please reopen and explain a bit more.
