### ISSUE TITLE
Carla error ros_compatibility

### ISSUE THREAD

**Issue by spanthr** [carla-simulator/carla#4367]
File "/home/shaurya/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/actor_factory.py", line 33, in <module>
    from carla_ros_bridge.marker_sensor import MarkerSensor
  File "/home/shaurya/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/marker_sensor.py", line 29, in <module>
    carla.CityObjectLabel.Buildings: ColorRGBA(r=70.0/255.0, g=70.0/255.0, b=70.0/255.0, a=0.8),
AttributeError: 'module' object has no attribute 'CityObjectLabel'
================================================================================REQUIRED process [carla_ros_bridge-2] has died!
process has died [pid 9094, exit code 1, cmd /home/shaurya/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py __name:=carla_ros_bridge __log:=/home/shaurya/.ros/log/36e001b0-dd7b-11eb-a982-94e6f7a668aa/carla_ros_bridge-2.log].
log file: /home/shaurya/.ros/log/36e001b0-dd7b-11eb-a982-94e6f7a668aa/carla_ros_bridge-2*.log
Initiating shutdown!
================================================================================
[carla_manual_control_ego_vehicle-5] killing on exit
[set_initial_pose_ego_vehicle-4] killing on exit
[carla_spawn_objects_shauryapc_9067_1718727163877865638-3] killing on exit
[carla_ros_bridge-2] killing on exit
Traceback (most recent call last):
  File "/home/shaurya/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py", line 378, in <module>
    main()
  File "/home/shaurya/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py", line 356, in main
    spawn_objects_node = CarlaSpawnObjects()
  File "/home/shaurya/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py", line 56, in __init__
    self.spawn_object_service = self.new_client(SpawnObject, "/carla/spawn_object")
  File "/home/shaurya/carla-ros-bridge/catkin_ws/src/ros-bridge/ros_compatibility/src/ros_compatibility/node.py", line 89, in new_client
    raise ROSException(e)
ros_compatibility.exceptions.ROSException: rospy shutdown
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by corkyw10** [comment]
@spanthr could you provide more context on your error please?

**Comment by zacgeiser** [comment]
Does any one found the solution for this error?

**Comment by zacgeiser** [comment]
or a good tutorial to install and launch Carla ros autoware without facing any error?

**Comment by jiangqianpeng** [comment]
add the path into .bashrc
gedit ~/.bashrc
and add your path
export PYTHONPATH=SPYTHONPATH:~/carla/PythonApI/carla/dist/carla-0.9.13-py2.7-linux-x86-64.egg
make sure the python is version 2.7
