### ISSUE TITLE
As a noob,i don't know what's wrong with my code.

### ISSUE THREAD

**Issue by errorJY** [carla-simulator/carla#459]
# I change the manual_control.py just want to my car can drive along with the Lane centerline.So  I just drive my car from 73 to 81 at the  Town01.
[town_positions.pdf](https://github.com/carla-simulator/carla/files/2052582/town_positions.pdf)
but when i run my code,the Carla sever always restar.
`[2018.05.30-05.54.10:954][  1]LogCarlaServer: Warning: No control received from the client this frame!
[2018.05.30-05.54.11:020][  2]LogParticles: Warning: Spawning 37155 GPU particles in one frame[2]: P_GPU_particles_collision2/Particle Emitter
[2018.05.30-05.54.11:032][  2]LogCarlaServer: Warning: No control received from the client this frame!
[2018.05.30-05.54.11:835][  4]LogParticles: Warning: Spawning 37156 GPU particles in one frame[4]: P_GPU_particles_collision2/Particle Emitter
[2018.05.30-05.54.12:321][  4]LogCarlaServer: Warning: Client disconnected, server needs restart
[2018.05.30-05.54.12:321][  4]LogCarlaServer: Restarting the level...
[2018.05.30-05.54.12:365][  5]LogParticles: Warning: Spawning 37156 GPU particles in one frame[5]: P_GPU_particles_collision2/Particle Emitter
ERROR: tcpserver 0[2018.05.30-05.54.28:849][  5]LogCarlaServer: Warning: Failed to initialize, server needs restart
`
It's sad!
there is my code .
[PID_control .txt](https://github.com/carla-simulator/carla/files/2052590/PID_control.txt)

**Comment by errorJY** [comment]
I upgrade my code.
[M_manual.txt](https://github.com/carla-simulator/carla/files/2057441/M_manual.txt)

**Comment by errorJY** [comment]
There also are bugs...
`ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
Starting new episode...
Step 1 (0.5 FPS): 0.00 km/h, 0% other lane, 0% off-road                       
  Traceback (most recent call last):
  File "./M_manual.py", line 475, in <module>
    main()
  File "./M_manual.py", line 464, in main
    game.execute()
  File "./M_manual.py", line 166, in execute
    self._on_loop()
  File "./M_manual.py", line 230, in _on_loop
    control = self._get_keyboard_control(pygame.key.get_pressed())
  File "./M_manual.py", line 259, in _get_keyboard_control
    if self.M_open:
AttributeError: 'CarlaGame' object has no attribute 'M_open'

`

**Comment by errorJY** [comment]
Just as I thinked, I changed the M_open with the K_q.So I can enter the Carla,but my car will move...
That's my the newest code...Just have one PID control more than manual.py.
[M_manual .txt](https://github.com/carla-simulator/carla/files/2058991/M_manual.txt)
If you have interested at it and u have time,plz help me to sovel it.Thank u

**Comment by errorJY** [comment]
emmm the question of the car can not move,i had deal with #458 ,but when I press the key of Q.The car will rush until it kiss with the car and don't follow the lane.So I change it again. Strength the PID control and  limit the speed. 
`    def _on_loop(self):
        self._timer.tick()

        measurements, sensor_data = self.client.read_data()

        self._main_image = sensor_data.get('CameraRGB', None)
        self._mini_view_image1 = sensor_data.get('CameraDepth', None)
        self._mini_view_image2 = sensor_data.get('CameraSemSeg', None)
        self._lidar_measurement = sensor_data.get('Lidar32', None)

        # Print measurements every second.
        if self._timer.elapsed_seconds_since_lap() > 1.0:
            if self._city_name is not None:
                # Function to get car position on map.
                    map_position = self._map.convert_to_pixel([
                    measurements.player_measurements.transform.location.x,
                    measurements.player_measurements.transform.location.y,
                    measurements.player_measurements.transform.location.z])
                # Function to get orientation of the road car is in.
                    lane_orientation = self._map.get_lane_orientation([
                    measurements.player_measurements.transform.location.x,
                    measurements.player_measurements.transform.location.y,
                    measurements.player_measurements.transform.location.z])

                    self._print_player_measurements_map(
                    measurements.player_measurements,
                    map_position,
                    lane_orientation)
            else:
                self._print_player_measurements(measurements.player_measurements)

            # Plot position on the map as well.

            self._timer.lap()
        control = self.PID_control(pygame.key.get_pressed(),map_position,measurements.player_measurements)
`
the map_position had be stated ,but i cann't use it.... 
I need help ,Thx

**Comment by errorJY** [comment]
` # Print measurements every second.
     self.map_position = self._map.convert_to_pixel([
                measurements.player_measurements.transform.location.x,
                measurements.player_measurements.transform.location.y,
                measurements.player_measurements.transform.location.z])
    if self._timer.elapsed_seconds_since_lap() > 1.0:
        if self._city_name is not None:

            # Function to get car position on map.

               

            # Function to get orientation of the road car is in.

                lane_orientation = self._map.get_lane_orientation([
                measurements.player_measurements.transform.location.x,
                measurements.player_measurements.transform.location.y,
                measurements.player_measurements.transform.location.z])
                self._print_player_measurements_map(
                measurements.player_measurements,
                self.map_position,
                lane_orientation)
        else:
            self._print_player_measurements(measurements.player_measurements)

        # Plot position on the map as well.

        self._timer.lap()
    control = self.PID_control(pygame.key.get_pressed(),self.map_position,measurements.player_measurements)`
