### ISSUE TITLE
Problems while creating SUMO network using netconvert_carla.py

### ISSUE THREAD

**Issue by pei-li-u-m** [carla-simulator/carla#4709]
CARLA version: CARLA 0.9.12
Platform/OS: Ubuntu 20.04
While using netconvert_carla.py to create the SUMO network from a xodr file, it returned an error of  ```"FileNotFoundError: [Errno 2] No such file or directory: 'netconvert'"```

The following is the error message:
```
Traceback (most recent call last):
  File "netconvert_carla.py", line 541, in <module>
    netconvert_carla(args.xodr_file, args.output, args.guess_tls)
  File "netconvert_carla.py", line 521, in netconvert_carla
    _netconvert_carla_impl(xodr_file, output, tmpdir, guess_tls)
  File "netconvert_carla.py", line 377, in _netconvert_carla_impl
    result = subprocess.call(['netconvert',
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'netconvert'
``` 

The sumo in my PC was built from source file, but I did include ```$SUMO_HOME``` to the environment PATH.

**Comment by svanimisetti** [comment]
@pei-li-u-m - You have this issue as your $SUMO_HOME/bin folder is not on the path too. Add following to the path and I think you should be fine.

```Python
os.environ['PATH'] = os.pathsep.join(
    [os.path.join(os.getenv('SUMO_HOME'),'bin'),os.getenv('PATH')])
```

Also, adding the following to Python path will also help.
```Python
sys.path.append(os.path.join(os.getenv('SUMO_HOME'),'tools'))
sys.path.append(os.path.join(os.getenv('CARLA_HOME'), 'Co-Simulation/Sumo'))
```
