### ISSUE TITLE
Can't install python carla in Docker Ubuntu 18.04

### ISSUE THREAD

**Issue by clementperon** [carla-simulator/carla#4950]
Hi,

I tried to install the python carla module inside the Ubuntu 18.04 carla docker.

But seems that since 0.9.5 Python package can't be installed on the Docker.

Pip install will only install version 0.9.5

```
root@Clement-Blade14:/home/carla/PythonAPI/carla/dist# python3.7 -m pip show carla   
Name: carla
Version: 0.9.5
Summary: Python API for communicating with the CARLA server.
Home-page: https://github.com/carla-simulator/carla
Author: The CARLA team
Author-email: carla.simulator@gmail.com
License: MIT License
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
```

I can't install the version ship inside the Docker

```
root@Clement-Blade14:/home/carla/PythonAPI/carla/dist# python3.7 -m pip -vvv install carla-0.9.13-cp37-cp37m-manylinux_2_27_x86_64.whl
carla-0.9.13-cp37-cp37m-manylinux_2_27_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 330, in run
    wheel_cache
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 276, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 245, in add_requirement
    wheel.filename
pip.exceptions.InstallationError: carla-0.9.13-cp37-cp37m-manylinux_2_27_x86_64.whl is not a supported wheel on this platform.
```

**Comment by joel-mb** [comment]
Hi @clementperon,
You require `pip` version 20.3 or above to install the latest CARLA Python package. You can upgrade `pip` in the following way:
```
pip install --upgrade pip
```

After doing that, `pip` will find the newest versions of the CARLA Python API.
