### ISSUE TITLE
0.9.3 Carla GenerateProjectFiles.bat / Windows 10 compile failure due to FIPS policy

### ISSUE THREAD

**Issue by apiszcz** [carla-simulator/carla#4993]
https://carla.readthedocs.io/en/0.9.13/build_windows/

The following command
GenerateProjectFiles.bat

NOTE: I am not able to disable the feature per https://community.progress.com/s/article/Windows-Platform-FIPS-validated-crypto-message-appears-trying-to-access-Login-aspx-1307565986146

Generates
```
Setting up Unreal Engine 4 project files...
Binding IntelliSense data... 100%
Writing project files... 98%
ERROR: Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
          at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
          --- End of inner exception stack trace ---
          at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
          at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
          at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
          at System.Security.Cryptography.MD5.Create()
          at UnrealBuildTool.VCProjectFileGenerator.MakeMd5Guid(Byte[] Input) in C:\carla\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\VisualStudio\VCProjectFileGenerator.cs:line 437
          at UnrealBuildTool.VCProjectFileGenerator.GenerateProjectFolderGuids(String ParentPath, MasterProjectFolder Folder, IDictionary`2 Guids) in C:\carla\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\VisualStudio\VCProjectFileGenerator.cs:line 426
          at UnrealBuildTool.VCProjectFileGenerator.GenerateProjectFolderGuids(MasterProjectFolder RootFolder) in C:\carla\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\VisualStudio\VCProjectFileGenerator.cs:line 417
          at UnrealBuildTool.VCProjectFileGenerator.WriteMasterProjectFile(ProjectFile UBTProject, PlatformProjectGeneratorCollection PlatformProjectGenerators) in C:\carla\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\VisualStudio\VCProjectFileGenerator.cs:line 535
          at UnrealBuildTool.ProjectFileGenerator.WriteProjectFiles(PlatformProjectGeneratorCollection PlatformProjectGenerators) in C:\carla\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\ProjectFileGenerator.cs:line 2760
          at UnrealBuildTool.VCProjectFileGenerator.WriteProjectFiles(PlatformProjectGeneratorCollection PlatformProjectGenerators) in C:\carla\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\VisualStudio\VCProjectFileGenerator.cs:line 452
          at UnrealBuildTool.ProjectFileGenerator.GenerateProjectFiles(PlatformProjectGeneratorCollection PlatformProjectGenerators, String[] Arguments) in C:\carla\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\ProjectFileGenerator.cs:line 1045
          at UnrealBuildTool.GenerateProjectFilesMode.Execute(CommandLineArguments Arguments) in C:\carla\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\Modes\GenerateProjectFilesMode.cs:line 204
          at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in C:\carla\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 550

GenerateProjectFiles ERROR: UnrealBuildTool was unable to generate project files.
```

**Comment by apiszcz** [comment]
https://docs.microsoft.com/en-us/previous-versions/system-center/system-center-2012-R2/hh914094(v=sc.12)?redirectedfrom=MSDN

**Comment by apiszcz** [comment]
Work around for this issue

**FIX regeditor
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy
SET Enabled to 0

**Comment by apiszcz** [comment]
https://docs.microsoft.com/en-us/previous-versions/system-center/system-center-2012-R2/hh914094(v=sc.12)?redirectedfrom=MSDN

**Comment by apiszcz** [comment]
The above change permits introspection and successful compilation.
