### ISSUE TITLE
Error in Manual_control.py

### ISSUE THREAD

**Issue by RAAA-Alaguvel-Armstrong** [carla-simulator/carla#5011]

**Comment by RAAA-Alaguvel-Armstrong** [comment]
Traceback (most recent call last):
  File "/home/carla/opt/CarlaSimulator/PythonClient/carla/client.py", line 174, in _read_sensor_data
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manual_control.py", line 439, in <module>
    main()
  File "manual_control.py", line 428, in main
    game.execute()
  File "manual_control.py", line 164, in execute
    self._on_loop()
  File "manual_control.py", line 204, in _on_loop
    measurements, sensor_data = self.client.read_data()
  File "/home/carla/opt/CarlaSimulator/PythonClient/carla/client.py", line 127, in read_data
    return pb_message, dict(x for x in self._read_sensor_data())
  File "/home/carla/opt/CarlaSimulator/PythonClient/carla/client.py", line 127, in <genexpr>
    return pb_message, dict(x for x in self._read_sensor_data())
RuntimeError: generator raised StopIteration

**Comment by RAAA-Alaguvel-Armstrong** [comment]
I am getting the above error on executing the manual_control.py
I am using Ubuntu 20.04
Python 3.8 and Python 3.6
