### ISSUE TITLE
Building new vehicle failed [following the doc]

### ISSUE THREAD

**Issue by momala** [carla-simulator/carla#5219]
Hello all,

I recently tried to create my own vehicle in the simulator. I followed everything one by one, but in the end, I run the below command to test my car:

`python3 manual_control.py --filter Iseauto
`
"Iseauto" is my vehicle name. It shows me the following error:

```
Traceback (most recent call last):
  File "manual_control.py", line 1325, in <module>
    main()
  File "manual_control.py", line 1317, in main
    game_loop(args)
  File "manual_control.py", line 1214, in game_loop
    world = World(sim_world, hud, args)
  File "manual_control.py", line 217, in __init__
    self.restart()
  File "manual_control.py", line 246, in restart
    blueprint = random.choice(get_actor_blueprints(self.world, self._actor_filter, self._actor_generation))
  File "/usr/lib/python3.6/random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```
I couldn't find any clue for the error. Do you have any suggestions?
It seems that it doesn't matter if I input the vehicle name wrongly in the command. it shows again the error. 

CARLA version: 0.9.13
Platform/OS: Ubuntu 18.04

**Comment by momala** [comment]
> Hello all,
> 
> I recently tried to create my own vehicle in the simulator. I followed everything one by one, but in the end, I run the below command to test my car:
> 
> `python3 manual_control.py --filter Iseauto ` "Iseauto" is my vehicle name. It shows me the following error:
> 
> ```
> Traceback (most recent call last):
>   File "manual_control.py", line 1325, in <module>
>     main()
>   File "manual_control.py", line 1317, in main
>     game_loop(args)
>   File "manual_control.py", line 1214, in game_loop
>     world = World(sim_world, hud, args)
>   File "manual_control.py", line 217, in __init__
>     self.restart()
>   File "manual_control.py", line 246, in restart
>     blueprint = random.choice(get_actor_blueprints(self.world, self._actor_filter, self._actor_generation))
>   File "/usr/lib/python3.6/random.py", line 260, in choice
>     raise IndexError('Cannot choose from an empty sequence') from None
> IndexError: Cannot choose from an empty sequence
> ```
> 
> I couldn't find any clue for the error. Do you have any suggestions? It seems that it doesn't matter if I input the vehicle name wrongly in the command. it shows again the error.
> 
> CARLA version: 0.9.13 Platform/OS: Ubuntu 18.04

It was my mistake, It is already mentioned that the vehicle name should be in lower case while running the command. So There is no problem anymore!
