### ISSUE TITLE
Issue when  run with the editor 

### ISSUE THREAD

**Issue by crazyzxd** [carla-simulator/carla#528]
Hi ,I got another problem when i trying to run the carla within the unreal engine editor(cause i want customize the map) [follow this guide](https://carla.readthedocs.io/en/latest/faq/) .
After i run the python client, the terminal gives the following message:

```
carlaClient connected
Starting episode 0 .... start at:38
Traceback (most recent call last):
  File "client_example.py", line 360, in <module>
    main()
  File "client_example.py", line 347, in main
    run_carla_client(args)
  File "client_example.py", line 137, in run_carla_client
    measurements, sensor_data = client.read_data()
  File "/home/xxd/carla-release082/PythonClient/carla/client.py", line 127, in read_data
    return pb_message, dict(x for x in self._read_sensor_data())
  File "/home/xxd/carla-release082/PythonClient/carla/client.py", line 127, in <genexpr>
    return pb_message, dict(x for x in self._read_sensor_data())
  File "/home/xxd/carla-release082/PythonClient/carla/client.py", line 175, in _read_sensor_data
    yield self._parse_sensor_data(data)
  File "/home/xxd/carla-release082/PythonClient/carla/client.py", line 180, in _parse_sensor_data
    return parser.name, parser.parse_raw_data(data[4:])
  File "/home/xxd/carla-release082/PythonClient/carla/client.py", line 196, in parse_image
    return sensor.Image(frame_number, width, height, image_type, fov, data[24:])
  File "/home/xxd/carla-release082/PythonClient/carla/sensor.py", line 152, in __init__
    assert len(raw_data) == 4 * width * height
AssertionError
```

**Comment by nsubiron** [comment]
Hi @crazyzxd,

It seems you are using an old version of the client. If you compiled the simulator from source you should use the Python client in the repository.
