### ISSUE TITLE
raise IndexError('Cannot choose from an empty sequence') from None

### ISSUE THREAD

**Issue by omega1497** [carla-simulator/carla#5547]
'''>>> Creating camera {'x': -0.2, 'y': -0.55, 'z': 1.65, 'roll': 0, 'pitch': -10, 'yaw': 270, 'width': 1024, 'height': 768, 'fov': 90, 'sensor_label': 'camera8', 'sensor_type': 'camera'}
>>> Creating GNSS {'x': 1.5, 'y': 0, 'z': 2.4, 'roll': 0, 'pitch': 0, 'yaw': 0, 'sensor_label': 'gnss', 'sensor_type': 'gnss'}
>>> Creating camera {'x': -7, 'y': 0, 'z': 4, 'roll': 0, 'pitch': -25, 'yaw': 0, 'width': 1024, 'height': 768, 'fov': 90, 'sensor_label': 'camera9', 'sensor_type': 'camera'}
>>> Creating camera {'x': 0, 'y': 0, 'z': 100, 'roll': 0, 'pitch': -90, 'yaw': 90, 'width': 1024, 'height': 768, 'fov': 90, 'sensor_label': 'camera10', 'sensor_type': 'camera'}
>>> Creating LIDAR {'x': 0, 'y': 0, 'z': 2.0, 'roll': 0, 'pitch': 0, 'yaw': 0, 'channels': 32, 'range': 20000.0, 'lower_fov': -30, 'upper_fov': 15, 'points_per_second': 560000, 'rotation_frequency': 30, 'sensor_label': 'lidar', 'sensor_type': 'lidar'}
>> Creating Opponents
Traceback (most recent call last):
  File ".\dataset_generation.py", line 383, in <module>
    save_rgb_as_jpeg)
  File ".\dataset_generation.py", line 250, in run_use_case
    bp = random.choice(blueprint_library.filter(random.choice(VEHICLES_LIST)))
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python37\lib\random.py", line 261, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
PS C:\Users\Shadow\Desktop\joed\scripts>'''

**Comment by Blyron** [comment]
This needs more context.
