### ISSUE TITLE
IndexError: _Map_base::at

### ISSUE THREAD

**Issue by lzx-center** [carla-simulator/carla#5737]
**CARLA version**: 0.9.13
**Platform/O**S: ubuntu 18.04
**Problem you have experienced**:
I have built carla 0.9.13 myself, and use `make launch` command to run UE4 Editor. 
But when I tried to run the python script "manual_control.py",  error occured. The traceback are as follows:

```bash
Traceback (most recent call last):
  File "./manual_control.py", line 1328, in <module>
    main()
  File "./manual_control.py", line 1320, in main
    game_loop(args)
  File "./manual_control.py", line 1218, in game_loop
    controller = KeyboardControl(world, args.autopilot)
  File "./manual_control.py", line 379, in __init__
    world.player.set_autopilot(self._autopilot_enabled)
IndexError: _Map_base::at
```
the quite same error happends also in other script, like `automatic_control.py`, will arise same error:

```bash
Traceback (most recent call last):
  File "./automatic_control.py", line 846, in <module>
    main()
  File "./automatic_control.py", line 839, in main
    game_loop(args)
  File "./automatic_control.py", line 696, in game_loop
    traffic_manager = client.get_trafficmanager()
IndexError: _Map_base::at
```
Other script like `generate_traffic.py` will cause segment fault.

**What you expected to happen**:
Just like run the python script as the pre-build carla version.
**Steps to reproduce**:
Just build carla 0.9.13 and run the script.

**Comment by lzx-center** [comment]
I found that I use Update.sh download the wrong carla content. 
After download the right content, problem solved.
