### ISSUE TITLE
Export maps from Roadrunner to UE4

### ISSUE THREAD

**Issue by Into-sight** [carla-simulator/carla#5793]
HI Team,

I have successfully imported a simple map into UE4, but when I tried to import a complex map (1000mX1000m, with lots of trees and buildings), I failed.

CARLA version:0.9.13 (latest)
Unreal Engine : 4.26
Platform/OS:Windows 10
What you expected to happen: Map ingestion into UE4

Error:
C:\carla>make import ARGS="--package MapPackage --no-carla-materials"
-[Setup]: [Batch params]: --boost-toolset msvc-14.2 --package MapPackage --no-carla-materials
-[Setup]: Asynchronous jobs:  16
-[Setup]: Boost toolset:      msvc-14.2
-[Setup]: Install directory:  "C:\carla\Build\"
-[Setup]: Installing zlib...
    -[install_zlib]: [Batch params]: --build-dir "C:\carla\Build\"
    -[install_zlib]: A zlib installation already exists.
    -[install_zlib]: Delete "C:\carla\Build\zlib-install\" if you want to force a rebuild.
    -[install_zlib]: Exiting...
-[Setup]: Installing libpng...
    -[install_libpng]: [Batch params]: --build-dir "C:\carla\Build\" --zlib-install-dir "C:\carla\Build\zlib-install\"
    -[install_libpng]: A libpng installation already exists.
    -[install_libpng]: Delete "C:\carla\Build\libpng-1.2.37-install\" if you want to force a rebuild.
    -[install_libpng]: Exiting...
-[Setup]: Installing rpclib...
    -[install_rpclib]: [Batch params]: --build-dir "C:\carla\Build\"
    -[install_rpclib]: A rpclib installation already exists.
    -[install_rpclib]: Delete "C:\carla\Build\rpclib-install\" if you want to force a rebuild.
    -[install_rpclib]: Exiting...
-[Setup]: Installing Google Test...
    -[install_gtest]: [Batch params]: --build-dir "C:\carla\Build\"
    -[install_gtest]: A Google Test installation already exists.
    -[install_gtest]: Delete "C:\carla\Build\gtest-install\" if you want to force a rebuild.
    -[install_gtest]: Exiting...
-[Setup]: Installing "Recast & Detour"...
    -[install_recast]: [Batch params]: --build-dir "C:\carla\Build\"
    -[install_recast]: A "Recast & Detour" installation already exists.
    -[install_recast]: Delete "C:\carla\Build\recast-0b13b0-install\" if you want to force a rebuild.
    -[install_recast]: Exiting...
-[Setup]: Installing Boost...
    -[install_boost]: [Batch params]: --build-dir "C:\carla\Build\" --toolset msvc-14.2 --version 1.72.0 -j 16
    -[install_boost]: A Boost installation already exists.
    -[install_boost]: Delete "C:\carla\Build\boost-1.72.0-install\" if you want to force a rebuild.
    -[install_boost]: Exiting...
已复制         1 个文件。
已复制         1 个文件。
-[Setup]: Installing Xercesc...
    -[install_xercesc]: [Batch params]: --build-dir "C:\carla\Build\"
    -[install_xercesc]: A xerces installation already exists.
    -[install_xercesc]: Delete "C:\carla\Build\xerces-c-3.2.3-install\" if you want to force a rebuild.
    -[install_xercesc]: Exiting...
已复制         1 个文件。
-[Setup]: Installing Sqlite3
    -[install_sqlite3]: [Batch params]: --build-dir "C:\carla\Build\"
    -[install_sqlite3]: A Sqlite3 installation already exists.
    -[install_sqlite3]: Delete "C:\carla\Build\sqlite3-install" if you want to force a rebuild.
    -[install_sqlite3]: Exiting...
已复制         1 个文件。
-[Setup]: Installing PROJ
    -[install_proj]: [Batch params]: --build-dir "C:\carla\Build\"
    -[install_proj]: A PROJ installation already exists.
    -[install_proj]: Delete "C:\carla\Build\proj-install" if you want to force a rebuild.
    -[install_proj]: Exiting...
已复制         1 个文件。
-[Setup]: Creating "CMakeLists.txt.in"...
-[Setup]:
   ###########
   # SUCCESS #
   ###########

   IMPORTANT!

   All the CARLA library dependences should be installed now.
   (You can remove all "*-src" folders in C:\carla\Build\ directory)

   You only need the ASSET PACK with all the meshes and textures.

   This script provides the assets for CARLA 0.9.13:
   You can download the assets from here:

       http://carla-assets.s3.amazonaws.com/20211112_d5cfa12.tar.gz

   Unzip it in the "C:\carla\Unreal\CarlaUE4\Content\Carla\" folder.
   If you want another version, search it in C:\carla\Util\ContentVersions.txt.

-[BuildLibCarla]: [Batch params]: --server
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- Build debug:   ON
-- Build release: ON
-- Build test:    ON
-- Configuring done
-- Generating done
-- Build files have been written to: C:/carla/Build/libcarla-visualstudio
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

  carla_server.vcxproj -> C:\carla\Build\libcarla-visualstudio\LibCarla\cmake\server\Release\carla_server.lib
  carla_server_debug.vcxproj -> C:\carla\Build\libcarla-visualstudio\LibCarla\cmake\server\Release\carla_server_debug.lib
  -- Install configuration: "Release"
-[BuildLibCarla]: LibCarla server has been successfully installed in "C:\carla\Unreal\CarlaUE4\Plugins\Carla\CarlaDependencies\"!
C:\carla\Util\BuildTools\Import.py:353: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if key is not 'tiles':
Copying "C:\carla\Import\MapPackage\MyCity2\MyCity2.xodr" to "C:\carla\Util\DockerUtils\dist\MyCity2.xodr"
Commandlet: ['D:\\UnrealEngine/Engine/Binaries/Win64/UE4Editor', 'C:\\carla\\Unreal\\CarlaUE4\\CarlaUE4.uproject', '-run=ImportAssets', '-importSettings="C:\\carla\\importsetting.json"', '-nosourcecontrol', '-replaceexisting']
Copying "C:\carla\Import\MapPackage\MyCity2\MyCity2.fbx" to "C:\carla\Util\DockerUtils\dist\MyCity2.fbx"
WARNING: cannot parse georeference: ''. Using default values.
WARNING: Traffic sign 487 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 498 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 520 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 894 overlaps a driving lane. Moving out of the road...
WARNING: Failed to find suitable place for signal.
WARNING: Traffic sign 499 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 501 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 502 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 892 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 514 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 895 overlaps a driving lane. Moving out of the road...
WARNING: Failed to find suitable place for signal.
WARNING: Traffic sign 492 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 893 overlaps a driving lane. Moving out of the road...
WARNING: Failed to find suitable place for signal.
WARNING: Traffic sign 465 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 493 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 513 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 496 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 495 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 526 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 481 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 519 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 480 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 490 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 484 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 478 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 474 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 471 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 504 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 508 overlaps a driving lane. Moving out of the road...
WARNING: Traffic sign 507 overlaps a driving lane. Moving out of the road...
Location(x=-383.388153, y=-617.821228, z=0.000000)
Location(x=-380.942261, y=-617.099792, z=0.000000)
Location(x=-379.269409, y=-635.331238, z=0.000000)
Location(x=-381.829620, y=-634.761230, z=0.000000)
Location(x=-383.388153, y=-617.821228, z=0.000000)
Location(x=-382.953125, y=-636.355408, z=0.000000)
Location(x=-381.675171, y=-638.643127, z=0.000000)
Location(x=-406.076019, y=-643.677795, z=0.000000)
Location(x=-406.469360, y=-641.206055, z=0.000000)
Location(x=-382.953125, y=-636.355408, z=0.000000)
Location(x=-409.500916, y=-619.979736, z=0.000000)
Location(x=-411.045197, y=-617.737183, z=0.000000)
Location(x=-386.111359, y=-612.837036, z=0.000000)
Location(x=-385.905609, y=-615.344849, z=0.000000)
Location(x=-409.500916, y=-619.979736, z=0.000000)
Location(x=-411.034332, y=-638.539612, z=0.000000)
Location(x=-413.534271, y=-638.564392, z=0.000000)
Location(x=-413.667450, y=-620.769104, z=0.000000)
Location(x=-411.164398, y=-621.532288, z=0.000000)
Location(x=-411.034332, y=-638.539612, z=0.000000)
Location(x=-226.294464, y=-574.084229, z=0.000000)
Location(x=-226.361816, y=-576.626526, z=0.000000)
Location(x=-243.590698, y=-579.319153, z=0.000000)
Location(x=-244.211990, y=-576.886597, z=0.000000)
Location(x=-226.294464, y=-574.084229, z=0.000000)
Location(x=-229.481537, y=-557.978027, z=0.000000)
Location(x=-226.968216, y=-558.014099, z=0.000000)
Location(x=-225.345016, y=-575.484924, z=0.000000)
Location(x=-227.802002, y=-576.075439, z=0.000000)
Location(x=-229.481537, y=-557.978027, z=0.000000)
Location(x=-243.145615, y=-577.798645, z=0.000000)
Location(x=-245.662384, y=-577.711426, z=0.000000)
Location(x=-247.206375, y=-560.421448, z=0.000000)
Location(x=-244.749741, y=-559.810669, z=0.000000)
Location(x=-243.145615, y=-577.798645, z=0.000000)
Location(x=-246.343399, y=-561.700256, z=0.000000)
Location(x=-246.393890, y=-559.172180, z=0.000000)
Location(x=-229.228897, y=-556.273193, z=0.000000)
Location(x=-228.490646, y=-558.682922, z=0.000000)
Location(x=-246.343399, y=-561.700256, z=0.000000)
Loading...
Building...
Building navigation:
 - 628 x 291 cells
 - 0.2K verts, 0.1K tris
Finding walkable triangles...
Filter walkable surfaces...
Partition of walkable surfaces...
Remove walkable surfaces by agent raius...
Defining areas by material
Trace and simplify region contours...
Build polygons mesh from contours...
Create detail mesh...
Create Detour data from Recast poly mesh...
Creating navigation data...
Saving...
Copying "C:\carla\Util\DockerUtils\dist\MyCity2.bin" to "C:\carla\Unreal\CarlaUE4\Content\package\Maps\MyCity2\Nav\MyCity2.bin"
Traceback (most recent call last):
  File "C:\carla\Util\BuildTools\Import.py", line 637, in <module>
    main()
  File "C:\carla\Util\BuildTools\Import.py", line 634, in main
    import_assets_from_json_list(json_list, args.batch_size)
  File "C:\carla\Util\BuildTools\Import.py", line 454, in import_assets_from_json_list
    import_assets(package_name, dirname, props, maps, 0, 0, 0)
  File "C:\carla\Util\BuildTools\Import.py", line 390, in import_assets
    invoke_commandlet(commandlet_name, commandlet_arguments)
  File "C:\carla\Util\BuildTools\Import.py", line 211, in invoke_commandlet
    subprocess.check_call(command, shell=True)
  File "C:\Users\77550\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['D:\\UnrealEngine/Engine/Binaries/Win64/UE4Editor', 'C:\\carla\\Unreal\\CarlaUE4\\CarlaUE4.uproject', '-run=ImportAssets', '-importSettings="C:\\carla\\importsetting.json"', '-nosourcecontrol', '-replaceexisting']' returned non-zero exit status 3221225477.
make: *** [import] 错误 1

**Comment by ronyshaji** [comment]
> HI Team,
> 
> I have successfully imported a simple map into UE4, but when I tried to import a complex map (1000mX1000m, with lots of trees and buildings), I failed.
> 
> CARLA version:0.9.13 (latest) Unreal Engine : 4.26 Platform/OS:Windows 10 What you expected to happen: Map ingestion into UE4
> 
> Error: C:\carla>make import ARGS="--package MapPackage --no-carla-materials" -[Setup]: [Batch params]: --boost-toolset msvc-14.2 --package MapPackage --no-carla-materials -[Setup]: Asynchronous jobs: 16 -[Setup]: Boost toolset: msvc-14.2 -[Setup]: Install directory: "C:\carla\Build" -[Setup]: Installing zlib... -[install_zlib]: [Batch params]: --build-dir "C:\carla\Build" -[install_zlib]: A zlib installation already exists. -[install_zlib]: Delete "C:\carla\Build\zlib-install" if you want to force a rebuild. -[install_zlib]: Exiting... -[Setup]: Installing libpng... -[install_libpng]: [Batch params]: --build-dir "C:\carla\Build" --zlib-install-dir "C:\carla\Build\zlib-install" -[install_libpng]: A libpng installation already exists. -[install_libpng]: Delete "C:\carla\Build\libpng-1.2.37-install" if you want to force a rebuild. -[install_libpng]: Exiting... -[Setup]: Installing rpclib... -[install_rpclib]: [Batch params]: --build-dir "C:\carla\Build" -[install_rpclib]: A rpclib installation already exists. -[install_rpclib]: Delete "C:\carla\Build\rpclib-install" if you want to force a rebuild. -[install_rpclib]: Exiting... -[Setup]: Installing Google Test... -[install_gtest]: [Batch params]: --build-dir "C:\carla\Build" -[install_gtest]: A Google Test installation already exists. -[install_gtest]: Delete "C:\carla\Build\gtest-install" if you want to force a rebuild. -[install_gtest]: Exiting... -[Setup]: Installing "Recast & Detour"... -[install_recast]: [Batch params]: --build-dir "C:\carla\Build" -[install_recast]: A "Recast & Detour" installation already exists. -[install_recast]: Delete "C:\carla\Build\recast-0b13b0-install" if you want to force a rebuild. -[install_recast]: Exiting... -[Setup]: Installing Boost... -[install_boost]: [Batch params]: --build-dir "C:\carla\Build" --toolset msvc-14.2 --version 1.72.0 -j 16 -[install_boost]: A Boost installation already exists. -[install_boost]: Delete "C:\carla\Build\boost-1.72.0-install" if you want to force a rebuild. -[install_boost]: Exiting... 已复制 1 个文件。 已复制 1 个文件。 -[Setup]: Installing Xercesc... -[install_xercesc]: [Batch params]: --build-dir "C:\carla\Build" -[install_xercesc]: A xerces installation already exists. -[install_xercesc]: Delete "C:\carla\Build\xerces-c-3.2.3-install" if you want to force a rebuild. -[install_xercesc]: Exiting... 已复制 1 个文件。 -[Setup]: Installing Sqlite3 -[install_sqlite3]: [Batch params]: --build-dir "C:\carla\Build" -[install_sqlite3]: A Sqlite3 installation already exists. -[install_sqlite3]: Delete "C:\carla\Build\sqlite3-install" if you want to force a rebuild. -[install_sqlite3]: Exiting... 已复制 1 个文件。 -[Setup]: Installing PROJ -[install_proj]: [Batch params]: --build-dir "C:\carla\Build" -[install_proj]: A PROJ installation already exists. -[install_proj]: Delete "C:\carla\Build\proj-install" if you want to force a rebuild. -[install_proj]: Exiting... 已复制 1 个文件。 -[Setup]: Creating "CMakeLists.txt.in"... -[Setup]: ###########
> 
> # SUCCESS
> ###########
> 
> IMPORTANT!
> 
> All the CARLA library dependences should be installed now. (You can remove all "*-src" folders in C:\carla\Build\ directory)
> 
> You only need the ASSET PACK with all the meshes and textures.
> 
> This script provides the assets for CARLA 0.9.13: You can download the assets from here:
> 
> ```
>    http://carla-assets.s3.amazonaws.com/20211112_d5cfa12.tar.gz
> ```
> 
> Unzip it in the "C:\carla\Unreal\CarlaUE4\Content\Carla" folder. If you want another version, search it in C:\carla\Util\ContentVersions.txt.
> 
> -[BuildLibCarla]: [Batch params]: --server -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044. -- Build debug: ON -- Build release: ON -- Build test: ON -- Configuring done -- Generating done -- Build files have been written to: C:/carla/Build/libcarla-visualstudio 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642 版权所有(C) Microsoft Corporation。保留所有权利。
> 
> carla_server.vcxproj -> C:\carla\Build\libcarla-visualstudio\LibCarla\cmake\server\Release\carla_server.lib carla_server_debug.vcxproj -> C:\carla\Build\libcarla-visualstudio\LibCarla\cmake\server\Release\carla_server_debug.lib -- Install configuration: "Release" -[BuildLibCarla]: LibCarla server has been successfully installed in "C:\carla\Unreal\CarlaUE4\Plugins\Carla\CarlaDependencies"! C:\carla\Util\BuildTools\Import.py:353: SyntaxWarning: "is not" with a literal. Did you mean "!="? if key is not 'tiles': Copying "C:\carla\Import\MapPackage\MyCity2\MyCity2.xodr" to "C:\carla\Util\DockerUtils\dist\MyCity2.xodr" Commandlet: ['D:\UnrealEngine/Engine/Binaries/Win64/UE4Editor', 'C:\carla\Unreal\CarlaUE4\CarlaUE4.uproject', '-run=ImportAssets', '-importSettings="C:\carla\importsetting.json"', '-nosourcecontrol', '-replaceexisting'] Copying "C:\carla\Import\MapPackage\MyCity2\MyCity2.fbx" to "C:\carla\Util\DockerUtils\dist\MyCity2.fbx" WARNING: cannot parse georeference: ''. Using default values. WARNING: Traffic sign 487 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 498 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 520 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 894 overlaps a driving lane. Moving out of the road... WARNING: Failed to find suitable place for signal. WARNING: Traffic sign 499 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 501 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 502 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 892 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 514 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 895 overlaps a driving lane. Moving out of the road... WARNING: Failed to find suitable place for signal. WARNING: Traffic sign 492 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 893 overlaps a driving lane. Moving out of the road... WARNING: Failed to find suitable place for signal. WARNING: Traffic sign 465 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 493 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 513 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 496 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 495 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 526 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 481 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 519 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 480 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 490 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 484 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 478 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 474 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 471 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 504 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 508 overlaps a driving lane. Moving out of the road... WARNING: Traffic sign 507 overlaps a driving lane. Moving out of the road... Location(x=-383.388153, y=-617.821228, z=0.000000) Location(x=-380.942261, y=-617.099792, z=0.000000) Location(x=-379.269409, y=-635.331238, z=0.000000) Location(x=-381.829620, y=-634.761230, z=0.000000) Location(x=-383.388153, y=-617.821228, z=0.000000) Location(x=-382.953125, y=-636.355408, z=0.000000) Location(x=-381.675171, y=-638.643127, z=0.000000) Location(x=-406.076019, y=-643.677795, z=0.000000) Location(x=-406.469360, y=-641.206055, z=0.000000) Location(x=-382.953125, y=-636.355408, z=0.000000) Location(x=-409.500916, y=-619.979736, z=0.000000) Location(x=-411.045197, y=-617.737183, z=0.000000) Location(x=-386.111359, y=-612.837036, z=0.000000) Location(x=-385.905609, y=-615.344849, z=0.000000) Location(x=-409.500916, y=-619.979736, z=0.000000) Location(x=-411.034332, y=-638.539612, z=0.000000) Location(x=-413.534271, y=-638.564392, z=0.000000) Location(x=-413.667450, y=-620.769104, z=0.000000) Location(x=-411.164398, y=-621.532288, z=0.000000) Location(x=-411.034332, y=-638.539612, z=0.000000) Location(x=-226.294464, y=-574.084229, z=0.000000) Location(x=-226.361816, y=-576.626526, z=0.000000) Location(x=-243.590698, y=-579.319153, z=0.000000) Location(x=-244.211990, y=-576.886597, z=0.000000) Location(x=-226.294464, y=-574.084229, z=0.000000) Location(x=-229.481537, y=-557.978027, z=0.000000) Location(x=-226.968216, y=-558.014099, z=0.000000) Location(x=-225.345016, y=-575.484924, z=0.000000) Location(x=-227.802002, y=-576.075439, z=0.000000) Location(x=-229.481537, y=-557.978027, z=0.000000) Location(x=-243.145615, y=-577.798645, z=0.000000) Location(x=-245.662384, y=-577.711426, z=0.000000) Location(x=-247.206375, y=-560.421448, z=0.000000) Location(x=-244.749741, y=-559.810669, z=0.000000) Location(x=-243.145615, y=-577.798645, z=0.000000) Location(x=-246.343399, y=-561.700256, z=0.000000) Location(x=-246.393890, y=-559.172180, z=0.000000) Location(x=-229.228897, y=-556.273193, z=0.000000) Location(x=-228.490646, y=-558.682922, z=0.000000) Location(x=-246.343399, y=-561.700256, z=0.000000) Loading... Building... Building navigation:
> 
> * 628 x 291 cells
> * 0.2K verts, 0.1K tris
>   Finding walkable triangles...
>   Filter walkable surfaces...
>   Partition of walkable surfaces...
>   Remove walkable surfaces by agent raius...
>   Defining areas by material
>   Trace and simplify region contours...
>   Build polygons mesh from contours...
>   Create detail mesh...
>   Create Detour data from Recast poly mesh...
>   Creating navigation data...
>   Saving...
>   Copying "C:\carla\Util\DockerUtils\dist\MyCity2.bin" to "C:\carla\Unreal\CarlaUE4\Content\package\Maps\MyCity2\Nav\MyCity2.bin"
>   Traceback (most recent call last):
>   File "C:\carla\Util\BuildTools\Import.py", line 637, in 
>   main()
>   File "C:\carla\Util\BuildTools\Import.py", line 634, in main
>   import_assets_from_json_list(json_list, args.batch_size)
>   File "C:\carla\Util\BuildTools\Import.py", line 454, in import_assets_from_json_list
>   import_assets(package_name, dirname, props, maps, 0, 0, 0)
>   File "C:\carla\Util\BuildTools\Import.py", line 390, in import_assets
>   invoke_commandlet(commandlet_name, commandlet_arguments)
>   File "C:\carla\Util\BuildTools\Import.py", line 211, in invoke_commandlet
>   subprocess.check_call(command, shell=True)
>   File "C:\Users\77550\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
>   raise CalledProcessError(retcode, cmd)
>   subprocess.CalledProcessError: Command '['D:\UnrealEngine/Engine/Binaries/Win64/UE4Editor', 'C:\carla\Unreal\CarlaUE4\CarlaUE4.uproject', '-run=ImportAssets', '-importSettings="C:\carla\importsetting.json"', '-nosourcecontrol', '-replaceexisting']' returned non-zero exit status 3221225477.
>   make: *** [import] 错误 1

How did you export the map from carla ?
