### ISSUE TITLE
Can't start Carla on specific computer

### ISSUE THREAD

**Issue by manolotis** [carla-simulator/carla#5970]
Hello, I'm really struggling using Carla in a computer where I need it to work. I tried the same installation steps in a different computer I own (same OS) and everything worked like a charm on the first try. My main problem at the moment is that after a certain point, I do not know what else to try or how to proceed debugging, so with this post I hope someone can give me a solution or at least point me to the right resources to continue debugging.

**CARLA version:** 0.9.13. Also tried in 0.9.12 and 0.9.11, facing the same or similar issues (expanded below)
**Platform/OS:** Ubuntu 20.04 on an HP ZBook Studio G5 (GPU Quadro P2000 Mobile)
**Problem you have experienced: 2 things (so far):**
1. I try to launch Carla executing `CarlaUE4.sh`. A window briefly appears and shuts down, after which I see this output in the terminal: 
```
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Serial number of failed request:  318
  Current serial number in output stream:  328
terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Signal 6 caught.
Segmentation fault (core dumped)
```
2. In the past I already encountered this on other computers, and prevented it using opengl with `CarlaUE4.sh -opengl`, so I suppose there is some issue with vulkan. In the past this did the trick, but now when I downgrade to Carla 0.9.11 (since after that it's only vulkan) and try again, the server starts but when running python script that requires the traffic manager I get the following error: 
```
Traceback (most recent call last):
  File "manual_control.py", line 1325, in <module>
    main()
  File "manual_control.py", line 1317, in main
    game_loop(args)
  File "manual_control.py", line 1215, in game_loop
    controller = KeyboardControl(world, args.autopilot)
  File "manual_control.py", line 376, in __init__
    world.player.set_autopilot(self._autopilot_enabled)
RuntimeError: trying to create rpc server for traffic manager; but the system failed to create because of bind error.
```
I also tried Carla 0.9.13 with the parameter "-RenderOffScreen" and the server starts, but trying to run Python examples results in the same error.

**What you expected to happen**: I expected it to start the Carla server and allow me to run the python examples that come in the PythonAPI folder. 

Steps to reproduce (I suppose you won't be able to reproduce them): 1. Run  `CarlaUE4.sh` and get the error mentioned above;  or 2. run `CarlaUE4.sh -RenderOffScreen` and `python3 manual_control.py` and get the error mentioned above; or 3. downgrade to carla 0.9.11, run `CarlaUE4.sh -opengl` and `python3 manual_control.py`, and get the error mentioned above.

**Other information (documentation you consulted, workarounds you tried):**
General things: 
- I tried different Carla installation methods, the Debian package installation and downloading the different releases from the repo. I have not tried building it (tho I did in the past and did not solve my problems with starting the server using vulkan).
- Depending on the Carla version, I tried Python versions 3.7 and 3.8 to run the Python examples.

Specifically regarding the first problem (Not able to start the server with graphics with Vulkan):
- As mentioned above I tried `CarlaUE4.sh -RenderOffScreen` and `CarlaUE4.sh -opengl` in Carla versions 0.9.13, 0.9.12 and 0.9.11 (whenever the version allowed the parameter). The server starts this way, but then I run into extra problems trying to run Python examples.
- Ensured I have Vulkan and Nvidia drivers installed on my machine. When running `nvidia-smi` I see the version I have is 510.47.03 . I see on the Nvidia website the very last drivers for my platform are 515.86.01, but unless it's strictly required I would prefer not updating this, since often when I do something else gets messed up and Tensorflow/Pytorch no longer recognize my GPU. When I run `vulkaninfo` I see my version is 1.2.131 and a ton of extra input I don't really understand. 

Specifically regarding the traffic manager issue: 
The error hints that the port is busy.  Following some suggestions in this [similar issue from the scenario_runner repo](https://github.com/carla-simulator/scenario_runner/issues/722), or in  #3543, I try killing all Python processes to free that port. The problem persists, but upon checking if there is anything using port 8000 (e.g. with `lsof -i :8000`), nothing seems to be occupying it.

In the past I also tried: 
Setting up the server in a more powerful PC that just sits at home, and connect remotely. However, this came with many other networking headaches that I would really prefer to avoid.

Any suggestions? I travel for work a lot and I really need the install on a machine that I can carry around. 
Thank you in advance.

----------------------- Update --------------------------
Turns out there was indeed something already occupying port 8000. "docker-pr" was running under the user root... And when trying to list processes occupying port 8000 `lsof -i :8000`, it simply didn't show... when running with elevated permissions `sudo lsof -i :8000` it shows. So now I can at least run Carla headless and things seem to work so far, but all my problems starting the server with graphics (with Vulkan) as mentioned above still remain. 

----------------------- Update 2 --------------------------
On [https://developer.nvidia.com/vulkan-driver](https://developer.nvidia.com/vulkan-driver) I could find my GPU (although they only listed Quadro P2000 and not Quadro P2000 Mobile, which is technically the one I have. Not sure if it makes a difference). Based on this I think my GPU should be supported. 

I found this list under the section regarding the 1.3 drivers, and I had 1.2. Just to make sure I got the latest drivers, adding `ppa:kisak/kisak-mesa` to my repositories. After that update, I got some other Mesa error when launching `./CarlaUE4.sh -RenderOffScreen`:
```
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
MESA: error: failed to load D3D12
```
So I reverted back to the previous drivers with ppa-purge, and now I can again run Carla headless, but I really want to know what could be causing my problems launching Carla with graphics.

P.S: I can run the `manual_control.py` example and a window appears where I can see the carla server is running and I can navigate around (super slow, but that's due to my hardware I suppose)

**Comment by PlayWeird** [comment]
I'm having the same issue.

CARLA version: 0.9.14
Platform/OS: ASUS Zephyrus M16 '22 / Ubuntu 20.04 on 12th Gen Intel® Core™ i9-12900H × 20
GPU: NVIDIA GeForce RTX 3080 Ti Laptop: Driver Version: 530.41.03    CUDA Version: 12.1
Vulkan Instance Version: 1.3.243

Any help would be greatly appreciated.

**Comment by kmodexc** [comment]
I have the same issue on a Surface Book 3 with Ubuntu 22 and GTX 1660 Ti

**Comment by abol-karimi** [comment]
I had the same issue with both 0.9.14 and 0.9.15, on my Alienware laptop. It seems that the problem is due to the fact that the laptop has two graphics processor: an Intel and an NVIDIA. Specifying the graphics adapter fixed it:
`./CarlaUE4.sh -ini:[/Script/Engine.RendererSettings]:r.GraphicsAdapter=2`

**Comment by Phoolore** [comment]
hi there. ChatGPT said I need vulcan
after
```
sudo apt install vulkan-tools
```
check with
```
vulkaninfo | less
```
and it worked, you can also try doing so with -nosound
```
./CarlaUE4.sh --quality-level=Low -nosound
```
