### ISSUE TITLE
Runtime Error when using the autopilot mode of manual.py in a custom map

### ISSUE THREAD

**Issue by john123741** [carla-simulator/carla#6278]
CARLA version: 0.9.14
Platform/OS: ubuntu 20.04
The problem you have experienced:  I made a customed opendrive map and load into carla. When I run the manual.py and use autopilot mode to drive the vehicle, after some seconds, the UI was off and the terminal showed these runtime errors.
```
Traceback (most recent call last):
  File "PythonAPI/examples/manual_control.py", line 1284, in game_loop
    world.tick(clock)
  File "PythonAPI/examples/manual_control.py", line 339, in tick
    self.hud.tick(self, clock)
  File "PythonAPI/examples/manual_control.py", line 695, in tick
    t = world.player.get_transform()
RuntimeError: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PythonAPI/examples/manual_control.py", line 1380, in <module>
    main()
  File "PythonAPI/examples/manual_control.py", line 1372, in main
    game_loop(args)
  File "PythonAPI/examples/manual_control.py", line 1297, in game_loop
    world.destroy()
  File "PythonAPI/examples/manual_control.py", line 364, in destroy
    self.player.destroy()
RuntimeError: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.

```
What you expected to happen: It should run without any runtime error.
Steps to reproduce:
1. put the map into Import Folder and "make import". 
2. Use the map in UE4 and play. 
3. Run manual.py and press "p" to switch to autopilot mode

The map is in the following link:
https://drive.google.com/drive/folders/1dxo6pljs70zOeylQqUwje1cnifozAaQk?usp=sharing

**Comment by bourbonbourbon** [comment]
Hello @john123741 were you able to fix this issue?
