### ISSUE TITLE
Error occurs when running 'make PythonAPI'

### ISSUE THREAD

**Issue by boxwayne** [carla-simulator/carla#6390]
CARLA version: 0.9.14
Platform/OS: Ubuntu 20.04.5
Python version: 3.7.6
Virtual environment: py3_3.8.10
Problem you have experienced: Error occurs when running 'make PythonAPI'
What you expected to happen: BuildPythonAPI.sh: Success!
Steps to reproduce: using 'build with source' method to build CARLA (provided at https://carla.readthedocs.io/en/0.9.14/build_linux/), after setting Unreal Engine environment variable, do 'make PythonAPI' step, and then error occurs in stage 'BuildPythonAPI.sh: Building Python API for Python 3.'
Other information (documentation you consulted, workarounds you tried):
the last part of output information in terminal is attached below

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

BuildOSM2ODR.sh: Success!
Using clang-10 as the CARLA compiler.
BuildPythonAPI.sh: Building Python API for Python 3.
setup.py:37: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
  linux_distro = distro.linux_distribution()[0]
compiling:
  - source/libcarla/libcarla.cpp
/home/bld/.local/lib/python3.8/site-packages/setuptools/dist.py:689: SetuptoolsDeprecationWarning: As setuptools moves its configuration towards `pyproject.toml`,
`setuptools.config.parse_configuration` became deprecated.

For the time being, you can use the `setuptools.config.setupcfg` module
to access a backward compatible API, but this module is provisional
and might be removed in the future.

  parse_configuration(self, self.command_options,
Traceback (most recent call last):
  File "setup.py", line 163, in <module>
    setup(
  File "/home/bld/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 160, in setup
    _install_setup_requires(attrs)
  File "/home/bld/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in _install_setup_requires
    dist.parse_config_files(ignore_option_errors=True)
  File "/home/bld/.local/lib/python3.8/site-packages/setuptools/dist.py", line 689, in parse_config_files
    parse_configuration(self, self.command_options,
  File "/home/bld/.local/lib/python3.8/site-packages/setuptools/config/__init__.py", line 29, in _wrapper
    return fn(*args, **kwargs)
  File "/home/bld/.local/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 187, in parse_configuration
    distribution._referenced_files.update(
AttributeError: 'MinimalDistribution' object has no attribute '_referenced_files'
make: *** [Util/BuildTools/Linux.mk:87: PythonAPI] Error 1

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

**Comment by boxwayne** [comment]
Already solved. Error comes because the virtual environment runs with python 3.8. Problem can be solved by switching to the virtual environment with python 3.7
