### ISSUE TITLE
Carla 0.8.4 server hangs

### ISSUE THREAD

**Issue by tomchen1000** [carla-simulator/carla#642]
Start Carla server 
```
SDL_VIDEODRIVER=offscreen ./CarlaUE4.sh /Game/Maps/Town02 -carla-server -benchmark -fps=5 -world-port=12000 -carla-no-hud
```

Have a a client like client_example.py to run episodes on the server, after 1000 episodes or so. 

Server hangs with this error:
```
[2018.07.31-11.11.39:424][ 97]LogCarla: == CARLA Settings ==============================================================
[2018.07.31-11.11.39:424][ 97]LogCarla: Last settings file loaded: <string-provided-by-client>
[2018.07.31-11.11.39:424][ 97]LogCarla: [CARLA/Server]
[2018.07.31-11.11.39:424][ 97]LogCarla: Networking = Enabled
[2018.07.31-11.11.39:424][ 97]LogCarla: World Port = 2000
[2018.07.31-11.11.39:424][ 97]LogCarla: Server Time-out = 10000 ms
[2018.07.31-11.11.39:424][ 97]LogCarla: Synchronous Mode = Enabled
[2018.07.31-11.11.39:424][ 97]LogCarla: Send Non-Player Agents Info = Enabled
[2018.07.31-11.11.39:424][ 97]LogCarla: [CARLA/LevelSettings]
[2018.07.31-11.11.39:424][ 97]LogCarla: Player Vehicle        = Default
[2018.07.31-11.11.39:424][ 97]LogCarla: Number Of Vehicles    = 1
[2018.07.31-11.11.39:424][ 97]LogCarla: Number Of Pedestrians = 0
[2018.07.31-11.11.39:424][ 97]LogCarla: Weather Id = 0
[2018.07.31-11.11.39:424][ 97]LogCarla: Seed Vehicle Spawner = 123456789
[2018.07.31-11.11.39:424][ 97]LogCarla: Seed Pedestrian Spawner = 123456789
[2018.07.31-11.11.39:424][ 97]LogCarla: Two-Wheeled Vehicles = Enabled
[2018.07.31-11.11.39:424][ 97]LogCarla: Found 16 available weather settings.
[2018.07.31-11.11.39:424][ 97]LogCarla:   * 0 - Default
[2018.07.31-11.11.39:424][ 97]LogCarla:   * 1 - ClearNoon
[2018.07.31-11.11.39:424][ 97]LogCarla:   * 2 - CloudyNoon
[2018.07.31-11.11.39:424][ 97]LogCarla:   * 3 - WetNoon
[2018.07.31-11.11.39:424][ 97]LogCarla:   * 4 - WetCloudyNoon
[2018.07.31-11.11.39:424][ 97]LogCarla:   * 5 - MidRainyNoon
[2018.07.31-11.11.39:424][ 97]LogCarla:   * 6 - HardRainNoon
[2018.07.31-11.11.39:425][ 97]LogCarla:   * 7 - SoftRainNoon
[2018.07.31-11.11.39:425][ 97]LogCarla:   * 8 - ClearSunset
[2018.07.31-11.11.39:425][ 97]LogCarla:   * 9 - CloudySunset
[2018.07.31-11.11.39:425][ 97]LogCarla:   * 10 - WetSunset
[2018.07.31-11.11.39:425][ 97]LogCarla:   * 11 - WetCloudySunset
[2018.07.31-11.11.39:425][ 97]LogCarla:   * 12 - MidRainSunset
[2018.07.31-11.11.39:425][ 97]LogCarla:   * 13 - HardRainSunset
[2018.07.31-11.11.39:425][ 97]LogCarla:   * 14 - SoftRainSunset
[2018.07.31-11.11.39:425][ 97]LogCarla:   * 15 - ClearNight
[2018.07.31-11.11.39:425][ 97]LogCarla: [CARLA/QualitySettings]
[2018.07.31-11.11.39:425][ 97]LogCarla: Quality Settings = None
[2018.07.31-11.11.39:425][ 97]LogCarla: [CARLA/Sensor]
[2018.07.31-11.11.39:425][ 97]LogCarla: Added 0 sensors.
[2018.07.31-11.11.39:425][ 97]LogCarla: Semantic Segmentation = Disabled
[2018.07.31-11.11.39:425][ 97]LogCarla: ================================================================================
[2018.07.31-11.11.39:432][ 97]LogWorld: Bringing up level for play took: 0.136663
[2018.07.31-11.11.39:435][ 97]LogCarlaServer: Sending 83 available start positions
[2018.07.31-11.11.39:435][ 97]LogCarlaServer: Sending 0 sensor descriptions
[2018.07.31-11.11.39:435][ 97]LogCarlaServer: Episode start received: { StartIndex = 28 }
[2018.07.31-11.11.39:437][ 97]LogCarla: Changing weather settings to "Default"
[2018.07.31-11.11.39:437][ 97]LogCarlaServer: Ready to play, notifying client
[2018.07.31-11.11.39:439][ 97]LogCarla: Found 83 PlayerStart positions for spawning vehicles
[2018.07.31-11.11.39:463][ 97]LogCarla: Spawned all 1 requested vehicles
[2018.07.31-11.11.39:464][ 97]LogLoad: Took 2.872299 seconds to LoadMap(/Game/Maps/Town02)
ERROR: tcpserver 0 : error reading message: Operation canceled
[2018.07.31-11.19.34:102][199]LogScript: Warning: FLatentActionManager::ProcessLatentActions: CallbackTarget is None.
```

Client have a log like this:
```
Traceback (most recent call last):
  File "/home/user/client/carla/tcp.py", line 87, in _read_n
    data = self._socket.recv(length)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/client/client_code", line 275, in reset
    self.client.load_settings(settings)
  File "/home/user/client/carla/client.py", line 70, in load_settings
    return self._request_new_episode(carla_settings)
  File "/home/user/client/carla/client.py", line 168, in _request_new_episode
    data = self._world_client.read()
  File "/home/user/client/carla/tcp.py", line 73, in read
    header = self._read_n(4)
  File "/home/user/client/carla/tcp.py", line 89, in _read_n
    self._reraise_exception_as_tcp_error('failed to read data', exception)
  File "/home/user/client/carla/tcp.py", line 97, in _reraise_exception_as_tcp_error
    raise TCPConnectionError('%s%s: %s' % (self._logprefix, message, exception))
carla.tcp.TCPConnectionError: (localhost:2000) failed to read data: timed out
```

**Comment by felipecode** [comment]
This is related to SDL solution for running offscreen. It is not working properly.
Try this solution :  
http://carla.readthedocs.io/en/latest/carla_headless/

**Comment by tomchen1000** [comment]
That solution requires sudo permission, which doesn't work for my environment. 

I also try the docker approach (http://carla.org/2018/06/08/release-0.8.3/) to workaround the sudo permission requirement. However, docker approach also set SDL_VIDEODRIVER to offscreen, and also has this connection issue. 

Does that mean the Carla doesn't really support docker?

Any fix to make this SDL solution for running offscreen to work?

**Comment by felipecode** [comment]
Hey @tomchen1000 
With docker it is working fine for me.
Have you tried already ?

**Comment by tomchen1000** [comment]
What could fix the issue by using the docker approach? It set SDL_VIDEODRIVER to offscreen too:

```
ENV SDL_VIDEODRIVER=offscreen
```

**Comment by Florence-C** [comment]
Hi @tomchen1000 

I'm experiencing the same issue with carla docker 8.2. 

Did you find a way to fix it ? 

thanks

**Comment by shahabty** [comment]
Hello, I am experiencing the same issue
