### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by prabanjanGITHUB** [carla-simulator/carla#6527]
C:\WINDOWS\system32>pip3 install carla
Collecting carla
  Using cached carla-0.9.5.tar.gz (3.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\praba\AppData\Local\Temp\pip-build-env-5y9mabhj\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\praba\AppData\Local\Temp\pip-build-env-5y9mabhj\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\praba\AppData\Local\Temp\pip-build-env-5y9mabhj\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\praba\AppData\Local\Temp\pip-build-env-5y9mabhj\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 114, in <module>
        File "<string>", line 75, in get_libcarla_extensions
      FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dependencies/lib'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
![Capturegit](https://github.com/carla-simulator/carla/assets/135314752/7479396f-820c-4ea0-88e9-6c6ca05202b1)

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I am trying to install carla 9.14 on windows 10. I installed all the Pre-requirement software and packages, but while using pip3 install carla facing the above error, can anyone kindly help?

**Comment by zienchan** [comment]
I had the same problem, but in my case, downgrading the Python version from 3.11 to 3.8 solved the problem.
