### ISSUE TITLE
some problem with the release of carla 0.9.0

### ISSUE THREAD

**Issue by meixialin** [carla-simulator/carla#653]
I failed when I tried to run the new release .I follow the document and run the example script with python example.py , but I receive the response.
```
Traceback (most recent call last):
  File "example.py", line 114, in <module>
    main(add_a_camera=False, enable_autopilot=True)
  File "example.py", line 43, in main
    client = carla.Client('localhost', 2000)
AttributeError: 'module' object has no attribute 'Client'
```
Could you please tell me how to solve it ? Thank you !

**Comment by StarryFire** [comment]
Did you find the solution for this? I have the same problem.

**Comment by StarryFire** [comment]
Ok, solved it. 
You probably have anaconda installed on your system, so when you run 'python example.py' it uses the Anaconda environment python and not the one that is native to your system.
So, you will have to edit ~/.bashrc and comment the path to anaconda python

If you are using the compiled version of Carla, then all will work fine.
If you built Carla from the source, then will have to first run 'make PythonAPI', this will generate a .egg file in PythonAPI/dist/, now go into the example.py and edit the path to the .egg file accordingly
Now, the script should run fine on the source version too.

**Comment by meixialin** [comment]
I didn't install anaconda,and I change the path to the .egg file as you say,but it didn't work.The result just as the same as before.

**Comment by goksanisil23** [comment]
@StarryFire thanks for the solution. I can run the 'make PythonAPI', and it claims that it has successfully installed Carla lib in "C:/carla/PythonAPI\dist", but the dist folder actually doesnt exist. Have you built it on a Windows machine or Linux ?

**Comment by wolfsubak** [comment]
I got same issue and there is only the 2.7 egg built in my dist folder.
The weird part: it was working well until I tried to use it with ros.

```
======================================================================
ERROR: test_default_values (test.test_transform.testLocation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/MyUsername/carla/PythonAPI/test/test_transform.py", line 14, in test_default_values
    location = carla.Location()
AttributeError: 'module' object has no attribute 'Location'
======================================================================
ERROR: test_client_version (test.test_client.testClient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wolf/MyUsername/carla/PythonAPI/test/test_client.py", line 17, in test_client_version
    c = carla.Client('localhost', 8080)
AttributeError: 'module' object has no attribute 'Client'

----------------------------------------------------------------------

```

**Comment by pbaj** [comment]
I changed the path in example.py to the one as @StarryFire suggested and uninstalled anaconda. I yet get the same error. Can you please help with this. @meixialin were you able to solve the problem?

**Comment by matthew-rococo** [comment]
i suggest you first "make clean" , and then "make launch" , and then "make PythonAPI", maybe this will correct your problem

**Comment by mshaheerm** [comment]
![capture](https://user-images.githubusercontent.com/40594242/46462151-f1d95300-c7c0-11e8-9145-06156380dfa3.JPG)
I am trying to `make PythonAPI` from the main carla folder but it raises these build errors. how can i fix them?

**Comment by iFuSiiOnzZ** [comment]
Check that `py` is available in you system. Open and command line and type `py`, it should open the default python version.

**Comment by sunpochin** [comment]
I just encountered this issue, the cause might be I installed PythonClient from pre-compiled version 0.8.4 
using this:
"pip2 install -e .  --user --upgrade"
https://github.com/carla-simulator/carla/tree/master/carla_ros_bridge

After uninstall it  "pip uninstall carla" 
now my 
"python example.py" cmd won't find the incorrect version of carla.

**Comment by gauravkumar22927** [comment]
I SOLVED IT ...
JUST INSTALL PYTHON 3.7 VERSION 64 BIT ONLY NOT 32 BIT IF YOUR COMPUTER IS 64 BIT 
this was cause of all error and install all packages "py -m pip install pkg_name" in **requirement.txt of all place**. requirement.txt will be at 2 places check it and one download is enough 2.9 gb dont go for other download.

**Comment by geonational** [comment]
Thanks gauravkumar22927, I was trying to run it with python 3.8 64-bit, but is has to be 3.7 64-bit as you said.
