### ISSUE TITLE
Core dumped with generate_traffic.py

### ISSUE THREAD

**Issue by Andrey949101** [carla-simulator/carla#6843]

**Comment by Andrey949101** [comment]
CARLA version 0.9.14
Python 3.10
Ubuntu 22

when I try to run the script generate_traffic.py an error occurs. I read about it on other links and tried all the methods to solve it (changed CALL_RETURNING_OPTIONAL(cc::World, GetRandomLocationFromNavigation)) in the file World.cpp , fixed the files libcarla.cpp and Client.cpp ), but nothing helped.
CARLA gives the following problem (text from gdb):

Starting program: /usr/bin/python3 generate_traffic.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff35ff640 (LWP 367500)]
[New Thread 0x7ffff2dfe640 (LWP 367501)]
[New Thread 0x7ffff25fd640 (LWP 367502)]
[New Thread 0x7ffff1dfc640 (LWP 367503)]
[New Thread 0x7ffff15fb640 (LWP 367504)]
[New Thread 0x7ffff0dfa640 (LWP 367505)]
[New Thread 0x7fffdbfff640 (LWP 367506)]
[New Thread 0x7fffdb7fe640 (LWP 367507)]
[New Thread 0x7fffdaffd640 (LWP 367508)]
[New Thread 0x7fffda7fc640 (LWP 367509)]
[New Thread 0x7fffd9ffb640 (LWP 367510)]
[New Thread 0x7fffd97fa640 (LWP 367511)]
[New Thread 0x7fffd8ff9640 (LWP 367512)]
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.14-6-g43b5e7064 
WARNING: Simulator API version  = 0.9.14-6-g43b5e7064-dirty 
[New Thread 0x7fffbbfff640 (LWP 367513)]
[New Thread 0x7fffbb7fe640 (LWP 367514)]
[New Thread 0x7fffbaffd640 (LWP 367516)]
[Thread 0x7fffbaffd640 (LWP 367516) exited]
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x0000555555681092 in PyType_GenericAlloc ()
(gdb) bt
#0  0x0000555555681092 in PyType_GenericAlloc ()
#1  0x00007ffff5bbb4fd in boost::python::objects::make_instance_impl<carla::geom::Location, boost::python::objects::value_holder<carla::geom::Location>, boost::python::objects::make_instance<carla::geom::Location, boost::python::objects::value_holder<carla::geom::Location> > >::execute<boost::reference_wrapper<carla::geom::Location const> const> (x=...)
    at dependencies/include/system/boost/python/object/make_instance.hpp:35
#2  boost::python::objects::class_cref_wrapper<carla::geom::Location, boost::python::objects::make_instance<carla::geom::Location, boost::python::objects::value_holder<carla::geom::Location> > >::convert (x=...)
    at dependencies/include/system/boost/python/object/class_wrapper.hpp:29
#3  0x00007ffff66f1f3f in boost::python::converter::detail::arg_to_python_base::arg_to_python_base(void const volatile*, boost::python::converter::registration const&) ()
   from /home/andrey/.cache/Python-Eggs/carla-0.9.14-py3.10-linux-x86_64.egg-tmp/carla/libcarla.cpython-310-x86_64-linux-gnu.so
#4  0x00007ffff5b81310 in boost::python::converter::detail::value_arg_to_python<carla::geom::Location>::value_arg_to_python (this=0x7fffffffc300, x=...)
    at dependencies/include/system/boost/python/converter/arg_to_python.hpp:205
#5  boost::python::converter::arg_to_python<carla::geom::Location>::arg_to_python (this=0x7fffffffc300, x=...)
    at dependencies/include/system/boost/python/converter/arg_to_python.hpp:252
#6  boost::python::api::object_initializer_impl<false, false>::get<carla::geom::--Type <RET> for more, q to quit, c to continue without paging--c
Location> (x=...) at dependencies/include/system/boost/python/object_core.hpp:289
#7  boost::python::api::object_base_initializer<carla::geom::Location> (x=...) at dependencies/include/system/boost/python/object_core.hpp:230
#8  boost::python::api::object::object<carla::geom::Location> (this=0x7fffffffc348, x=...) at dependencies/include/system/boost/python/object_core.hpp:247
#9  export_world()::$_109::operator()(carla::client::World const&) const (self=..., this=<optimized out>) at source/libcarla/World.cpp:312
#10 export_world()::$_109::__invoke(carla::client::World const&) (self=...) at source/libcarla/World.cpp:312
#11 0x00007ffff5c7c8d4 in boost::python::detail::invoke<boost::python::to_python_value<boost::python::api::object const&>, boost::python::api::object (*)(carla::client::World const&), boost::python::arg_from_python<carla::client::World const&> > (f=<optimized out>, ac0=..., rc=...) at dependencies/include/system/boost/python/detail/invoke.hpp:73
#12 boost::python::detail::caller_arity<1u>::impl<boost::python::api::object (*)(carla::client::World const&), boost::python::default_call_policies, boost::mpl::vector2<boost::python::api::object, carla::client::World const&> >::operator() (this=<optimized out>, args_=<optimized out>) at dependencies/include/system/boost/python/detail/caller.hpp:233
#13 0x00007ffff66e8ff3 in boost::python::objects::function::call(_object*, _object*) const () from /home/andrey/.cache/Python-Eggs/carla-0.9.14-py3.10-linux-x86_64.egg-tmp/carla/libcarla.cpython-310-x86_64-linux-gnu.so
#14 0x00007ffff66ea845 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) () from /home/andrey/.cache/Python-Eggs/carla-0.9.14-py3.10-linux-x86_64.egg-tmp/carla/libcarla.cpython-310-x86_64-linux-gnu.so
#15 0x00007ffff66efd42 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /home/andrey/.cache/Python-Eggs/carla-0.9.14-py3.10-linux-x86_64.egg-tmp/carla/libcarla.cpython-310-x86_64-linux-gnu.so
#16 0x00007ffff5c26ac3 in boost::python::detail::translate_exception<rpc::rpc_error, void (*)(rpc::rpc_error const&)>::operator() (this=<optimized out>, handler=..., f=..., translate=0x7ffff5b56ea0 <translator(rpc::rpc_error const&)>) at dependencies/include/system/boost/python/detail/translate_exception.hpp:46
#17 boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(rpc::rpc_error const&)> >::operator()<bool, boost::python::detail::translate_exception<rpc::rpc_error, void (*)(rpc::rpc_error const&)>, boost::_bi::rrlist2<boost::python::detail::exception_handler const&, boost::function0<void> const&> > (this=<optimized out>, f=..., a=...) at dependencies/include/system/boost/bind/bind.hpp:367
#18 boost::_bi::bind_t<bool, boost::python::detail::translate_exception<rpc::rpc_error, void (*)(rpc::rpc_error const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(rpc::rpc_error const&)> > >::operator()<boost::python::detail::exception_handler const&, boost::function0<void> const&> (this=<optimized out>, a1=..., a2=...) at dependencies/include/system/boost/bind/bind.hpp:1297
#19 boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<rpc::rpc_error, void (*)(rpc::rpc_error const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(rpc::rpc_error const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke (function_obj_ptr=..., a0=..., a1=...) at dependencies/include/system/boost/function/function_template.hpp:137
#20 0x00007ffff66efae9 in boost::python::handle_exception_impl(boost::function0<void>) () from /home/andrey/.cache/Python-Eggs/carla-0.9.14-py3.10-linux-x86_64.egg-tmp/carla/libcarla.cpython-310-x86_64-linux-gnu.so
#21 0x00007ffff66ea4d6 in boost::python::objects::function_call(_object*, _object*, _object*) () from /home/andrey/.cache/Python-Eggs/carla-0.9.14-py3.10-linux-x86_64.egg-tmp/carla/libcarla.cpython-310-x86_64-linux-gnu.so
#22 0x00005555556aa5eb in _PyObject_MakeTpCall ()
#23 0x00005555556c27bb in ?? ()
#24 0x00005555556a28a2 in _PyEval_EvalFrameDefault ()
#25 0x00005555556b470c in _PyFunction_Vectorcall ()
#26 0x000055555569ce0d in _PyEval_EvalFrameDefault ()
#27 0x000055555578de56 in ?? ()
#28 0x000055555578dcf6 in PyEval_EvalCode ()
#29 0x00005555557b87d8 in ?? ()
#30 0x00005555557b20bb in ?? ()
#31 0x00005555557b8525 in ?? ()
#32 0x00005555557b7a08 in _PyRun_SimpleFileObject ()
#33 0x00005555557b7653 in _PyRun_AnyFileObject ()
#34 0x00005555557aa41e in Py_RunMain ()
#35 0x0000555555780cad in Py_BytesMain ()
#36 0x00007ffff7c29d90 in __libc_start_call_main (main=main@entry=0x555555780c70, argc=argc@entry=2, argv=argv@entry=0x7fffffffcdc8) at ../sysdeps/nptl/libc_start_call_main.h:58
#37 0x00007ffff7c29e40 in __libc_start_main_impl (main=0x555555780c70, argc=2, argv=0x7fffffffcdc8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffcdb8) at ../csu/libc-start.c:392
#38 0x0000555555780ba5 in _start ()

Can someone help
