### ISSUE TITLE
ImportError error: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

### ISSUE THREAD

**Issue by nischalkhanal123** [carla-simulator/carla#7240]
CARLA version: 0.9.15
OS: Ubuntu 22.04

I followed the tutorial for building CARLA from the source. After compiling the client and server, I wanted to test the simulator using the examples. While running the script, I get the following error:

> Traceback (most recent call last):
>   File "/home/nischalkhanal/carla/PythonAPI/examples/manual_control.py", line 83, in <module>
>     import carla
>   File "/home/nischalkhanal/carla/PythonAPI/examples/carla/__init__.py", line 8, in <module>
>     from .libcarla import *
> ImportError: /home/nischalkhanal/carla/PythonAPI/examples/carla/libcarla.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

Is there a way to fix this?

Thank you,
Nischal

**Comment by MarcelPiNacy** [comment]
Hi,

Do you still have this issue?

Marcel

**Comment by HansYeoh** [comment]
I have found the same problem as you, have you found a solution?
