### ISSUE TITLE
TrafficManager: "get_next_action" Raises "invalid unordered_map<K,T> key"

### ISSUE THREAD

**Issue by nayanua** [carla-simulator/carla#7303]
CARLA version: 0.9.15
Platform/OS: Windows 11 / Ubuntu 20.04
Problem you have experienced:
In my application, I need to continuously get next action of the carla.TrafficManager instance. However, the command "get_next_action(actor)" raises "invalid unordered_map<K, T> key" exception.

```python
import carla
import numpy as np
import math
import cv2
import time

class CarlaCity:
    def __init__(self, TrafficM, egoCar, client, world) -> None:
        self.TrafficControl = TrafficM
        self.egoCar = egoCar   
        self.client = client
        self.world = world

    def getNextPolicy(self):
        return self.TrafficControl.get_next_action(self.egoCar)
    


def camCallBack(img, dataDict):
    dataDict['img'] = np.reshape(img.raw_data, (img.height, img.width, 4))[:, :, :3]

def spawnActor(world, bpLib, spawnPoint, actorRoleName = 'hero'):
    bp = bpLib.filter('model3')[0]
    camBp = bpLib.filter('sensor.camera.rgb')[0]

    # wbp.set_attribute('role_name', actorRoleName)
    egoCar = world.spawn_actor(bp, spawnPoint)
    cam = world.spawn_actor(camBp, carla.Transform(carla.Location(z=2.4)), attach_to=egoCar)
    
    return egoCar, cam

def setSynchronus(world, tm):
    initSettings = world.get_settings()
    initSettings.synchronous_mode = True
    tm.set_synchronous_mode(True)
    world.apply_settings(initSettings)

    return world, tm

def close(world, tm, spawnedActors):
    #Disable synchronous mode and destroy all actors
    currentSettings = world.get_settings()
    currentSettings.synchronous_mode = True
    tm.set_synchronous_mode(True)
    world.apply_settings(currentSettings)

    for actor in spawnedActors:
        actor.destroy()

        
if __name__ == "__main__":
    client = carla.Client('localhost', 2000)
    world = client.get_world()
    bpLib = world.get_blueprint_library()
    spawns = world.get_map().get_spawn_points()
    trafficManager = client.get_trafficmanager()

    time.sleep(1)
    try:
        egoCar, cam = spawnActor(world, bpLib, spawns[2])
        trafficManager.ignore_lights_percentage(egoCar, 100)
        world, trafficManager = setSynchronus(world, trafficManager)
        city = CarlaCity(trafficManager, egoCar, client, world)
        while True:
            action = city.getNextPolicy()
            print(action)
            world.tick()
            time.sleep(0.1)

    except KeyboardInterrupt:
        close(world, trafficManager, [egoCar, cam])


    # dataDict = {'img': None}
    # time.sleep(1)
    # egoCar, cam = spawnActor(world, bpLib, spawns[2])

    # egoCar.set_autopilot(True)
    # trafficManager.ignore_lights_percentage(egoCar, 100)
    # while True:
    #     trafficManager.get_all_actions(egoCar)
    #     time.sleep(0.1)

```
Log: 

> INFO:  Found the required file in cache!  Carla/Maps/TM/Town10HD_Opt.bin 
WARNING: synchronous mode enabled with variable delta seconds. It is highly recommended to set 'fixed_delta_seconds' when running on synchronous mode.
Traceback (most recent call last):
  File "c:/Users/yigit/OpenAI/CARLA_sim/egocar_action_getter.py", line 65, in <module>
    action = city.getNextPolicy()
  File "c:/Users/yigit/OpenAI/CARLA_sim/egocar_action_getter.py", line 15, in getNextPolicy
    return self.TrafficControl.get_next_action(self.egoCar)
IndexError: invalid unordered_map<K, T> key

What you expected to happen: Next actions for the vehicle to be printed
Steps to reproduce: 

1. Load the default map
2. Spawn an actor
3. Assign Traffic Manager to that actor
4. Call "TrafficManager.get_next_action"

Other information (documentation you consulted, workarounds you tried):

- Does not work both in synchronous mode and asynchronous mode

**Comment by laoying36** [comment]
Hello, I have the same problem as you. Have you solved it?
