### ISSUE TITLE
AssertionError: ego action in ObjectDetectionScenario should be a dict

### ISSUE THREAD

**Issue by wang1528186571** [carla-simulator/carla#7484]
**This is wrong：**
WARNING: No InMemoryMap cache found. Setting up local map. This may take a while... 
Traceback (most recent call last):
  File "scripts/run.py", line 78, in <module>
    runner.run()
  File "/home/wang/Desktop/wjl-project/safebench/safebench/carla_runner.py", line 333, in run
    self.eval(data_loader)
  File "/home/wang/Desktop/wjl-project/safebench/safebench/carla_runner.py", line 266, in eval
    obs, rewards, _, infos = self.env.step(ego_actions=ego_actions, scenario_actions=scenario_actions)
  File "/home/wang/Desktop/wjl-project/safebench/safebench/gym_carla/env_wrapper.py", line 94, in step
    self.env_list[e_i].step_before_tick(processed_action, scenario_actions[action_idx])
  File "/home/wang/Desktop/wjl-project/safebench/safebench/gym_carla/env_wrapper.py", line 181, in step_before_tick
    self._env.step_before_tick(ego_action=ego_action, scenario_action=scenario_action)
  File "/home/wang/Desktop/wjl-project/safebench/safebench/gym_carla/envs/carla_env.py", line 296, in step_before_tick
    assert isinstance(ego_action, dict), 'ego action in ObjectDetectionScenario should be a dict'
AssertionError: ego action in ObjectDetectionScenario should be a dict
basic.yaml object_detection_stopsign.yaml failed!
Traceback (most recent call last):
  File "scripts/run.py", line 78, in <module>
    runner.run()
  File "/home/wang/Desktop/wjl-project/safebench/safebench/carla_runner.py", line 333, in run
    self.eval(data_loader)
  File "/home/wang/Desktop/wjl-project/safebench/safebench/carla_runner.py", line 266, in eval
    obs, rewards, _, infos = self.env.step(ego_actions=ego_actions, scenario_actions=scenario_actions)
  File "/home/wang/Desktop/wjl-project/safebench/safebench/gym_carla/env_wrapper.py", line 94, in step
    self.env_list[e_i].step_before_tick(processed_action, scenario_actions[action_idx])
  File "/home/wang/Desktop/wjl-project/safebench/safebench/gym_carla/env_wrapper.py", line 181, in step_before_tick
    self._env.step_before_tick(ego_action=ego_action, scenario_action=scenario_action)
  File "/home/wang/Desktop/wjl-project/safebench/safebench/gym_carla/envs/carla_env.py", line 296, in step_before_tick
    assert isinstance(ego_action, dict), 'ego action in ObjectDetectionScenario should be a dict'
AssertionError: ego action in ObjectDetectionScenario should be a dict

**Below is the code I use to jump to the last error message:**
![screenshot-20240422-144403](https://github.com/carla-simulator/carla/assets/139137698/26c90a22-4ab7-47fe-a20e-0b7c2e7c8b6a)

**Comment by wang1528186571** [comment]
Please help me！
