### ISSUE TITLE
ModuleNotFoundError: No module named 'tr'

### ISSUE THREAD

**Issue by qq1183713118** [carla-simulator/carla#8133]
CARLA   branche:dev-ue5
Platform/OS:Ubuntu 22.04.5 LTS

I built the UE5 package and ran it. When I executed the python3 script: performance_benchmark, it prompted that the tr module could not be found. I tried to install the tr module, but a new error occurred. Here I attach the log information.
I hope someone can solve my problem

`ubuntu@ubuntu-wfj:/data/Carla/Build/Package/Linux/PythonAPI/util$ python3 performance_benchmark.py`
`Traceback (most recent call last):
File "/data/Carla/Build/Package/Linux/PythonAPI/util/performance_benchmark.py", line 31, in <module>
    from tr import tr
ModuleNotFoundError: No module named 'tr'
`

`ubuntu@ubuntu-wfj:/data/Carla/Build/Package/Linux/PythonAPI/util$ pip install tr`
`Defaulting to user installation because normal site-packages is not writeable
Collecting tr
  Using cached tr-2.8.6-py3-none-manylinux1_x86_64.whl.metadata (459 bytes)
Using cached tr-2.8.6-py3-none-manylinux1_x86_64.whl (57.1 MB)
Installing collected packages: tr
Successfully installed tr-2.8.6`

`ubuntu@ubuntu-wfj:/data/Carla/Build/Package/Linux/PythonAPI/util$ python3 performance_benchmark.py`
`Traceback (most recent call last):
  File "/data/Carla/Build/Package/Linux/PythonAPI/util/performance_benchmark.py", line 31, in <module>
    from tr import tr
ImportError: cannot import name 'tr' from 'tr' (/home/ubuntu/.local/lib/python3.10/site-packages/tr/__init__.py)
`

**Comment by Blyron** [comment]
All scripts has been revisited and reviewed. Please try to do it agains with the available scripts
