### ISSUE TITLE
no module named  pkg_resources  for ros1 bridge source build carla0.9.15

### ISSUE THREAD

**Issue by violetsaber** [carla-simulator/carla#8336]
ubuntu 20.04 
source build caral 0.9.15
ros bridge about ros1
No module named pkg_resources

i just follow the step by official document and after  make launch in carla root to start UE4carla
and then source
source ~/carla-ros-bridge/catkin_ws/devel/setup.bash

roslaunch carla_ros_bridge carla_ros_bridge.launch

so i meet this question  could someone know how to solve this issue  thank you 
![problem carla](https://github.com/user-attachments/assets/6c28ebcb-ae79-4c6d-9a21-83aa9c762989)

i think i have already  attend the path in the bashrc 

File "/home/qinghuan/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 15, in <module>
    import pkg_resources
ImportError: No module named pkg_resources

================================================================================REQUIRED process [carla_ros_bridge-2] has died!
process has died [pid 8632, exit code 1, cmd /home/qinghuan/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py __name:=carla_ros_bridge __log:=/home/qinghuan/.ros/log/d35a44fc-9b72-11ef-b931-f7ac9c69d969/carla_ros_bridge-2.log].
log file: /home/qinghuan/.ros/log/d35a44fc-9b72-11ef-b931-f7ac9c69d969/carla_ros_bridge-2*.log
Initiating shutdown!
===============================================================================

**Comment by violetsaber** [comment]
I delete the folder and try again to download  ros bridge1 and then follow official document  the question i face 
 and i find a .sh  document in
![nopkgresources](https://github.com/user-attachments/assets/08d1ad82-3490-48a5-be00-28b0e39127d9)
 
qinghuan is my computer name  so  i think you may find the same .sh and then ./install_dependencies it  
 the question will solve but it will  bring new question to you  the python version isn't suit for carla 

so you can find this path   /home/qinghuan/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge

you can find a   named CARLA_VERSION  you can vim it     change the python question and other question  now  i am searching for answer    Trying to connect to localhost:2000
[ERROR] [1730817033.764335, 0.000000]: Error: time-out of 2000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000
[INFO] [1730817033.765634, 0.000000]: Shutting down...
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 572, in signal_shutdown
    h()
  File "/home/qinghuan/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 349, in destroy
    self.shutdown.set()
AttributeError: 'CarlaRosBridge' object has no attribute 'shutdown'
================================================================================REQUIRED process [carla_ros_bridge-2] has died!
process has finished cleanly
log file: /home/qinghuan/.ros/log/82289114-9b82-11ef-b931-f7ac9c69d969/carla_ros_bridge-2*.log
Initiating shutdown!
================================================================================
[carla_ros_bridge-2] killing on exit
