### ISSUE TITLE
Fail to run V2X sensor demo V2XDemo.py, blueprint 'sensor.other.v2x' not found

### ISSUE THREAD

**Issue by zhuoqizheng** [carla-simulator/carla#8439]
CARLA version: CARLA_0.9.15
Lib: ue4-dev
Platform/OS: Ubuntu 22.04.4 LTS

Problem you have experienced: 
Fail to run V2X sensor demo

`python PythonAPI/examples/V2XDemo.py `

Output: 
pygame 2.6.1 (SDL 2.28.4, Python 3.7.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO: listening to server 127.0.0.1:2000

Welcome to CARLA manual control.

Use ARROWS or WASD keys for control.

    W            : throttle
    ...   (skip some control commands)
    ESC          : quit

Traceback (most recent call last):
  File "PythonAPI/examples/V2XDemo.py", line 1419, in <module>
    main()
  File "PythonAPI/examples/V2XDemo.py", line 1411, in main
    game_loop(args)
  File "PythonAPI/examples/V2XDemo.py", line 1308, in game_loop
    world = World(sim_world, hud, args)
  File "PythonAPI/examples/V2XDemo.py", line 219, in __init__
    self.restart()
  File "PythonAPI/examples/V2XDemo.py", line 290, in restart
    self.v2x_sensor = V2XSensor(self.player, self.hud)
  File "PythonAPI/examples/V2XDemo.py", line 1022, in __init__
    bp = world.get_blueprint_library().find('sensor.other.v2x')
IndexError: blueprint 'sensor.other.v2x' not found
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 127 (sensor.other.collision) 
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 128 (sensor.other.gnss) 
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 129 (sensor.other.imu)

**Comment by zhuoqizheng** [comment]
rebuild the carla lib and pip installl the *.whl in dist folder. 

resulting another problem

  File "automatic_control.py", line 148, in restart
    blueprint_list = get_actor_blueprints(self.world, self._actor_filter, self._actor_generation)
  File "automatic_control.py", line 85, in get_actor_blueprints
    bps = world.get_blueprint_library().filter(filter)
ValueError: sticky_control: invalid value type
 
same as #8291
