### ISSUE TITLE
ImportError: No module named cv_bridge

### ISSUE THREAD

**Issue by overlapjho** [carla-simulator/carla#999]
Hi, I am trying to use carla_ros_bridge on precompiled 0.8.4 my carla_ros_bridge and PythonClient came from the latest branch. When I ran a test it gives me this error.
```... logging to /home/overlapjho/.ros/log/rostest-Jhomar-22883.log
[ROSUNIT] Outputting test results to /home/overlapjho/.ros/test_results/carla_ros_bridge/rostest-test_ros_bridge_client.xml
Traceback (most recent call last):
  File "/home/overlapjho/ros/catkin_ws_for_carla/src/carla_ros_bridge/src/carla_ros_bridge/client.py", line 9, in <module>
    from carla_ros_bridge.bridge import CarlaRosBridge
  File "/home/overlapjho/ros/catkin_ws_for_carla/src/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 16, in <module>
    from carla_ros_bridge.sensors import CameraHandler, LidarHandler
  File "/home/overlapjho/ros/catkin_ws_for_carla/src/carla_ros_bridge/src/carla_ros_bridge/sensors.py", line 8, in <module>
    from cv_bridge import CvBridge
ImportError: No module named cv_bridge
[Testcase: testtestTopics] ... ERROR!
ERROR: max time [20.0s] allotted for test [testTopics] of type [rostest/publishtest]
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/runner.py", line 148, in fn
    self.test_parent.run_test(test)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 132, in run_test
    return self.runner.run_test(test)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/launch.py", line 684, in run_test
    (test.time_limit, test.test_name, test.package, test.type))
--------------------------------------------------------------------------------

[ROSTEST]-----------------------------------------------------------------------


SUMMARY
 * RESULT: FAIL
 * TESTS: 0
 * ERRORS: 1
 * FAILURES: 0
```

**Comment by fabianoboril** [comment]
Hi,

It seems you are missing the ROS OpenCV bridge. You can install it (in case of Ubuntu) via apt-get install ros-kinetic-cv-bridge. And of course, your ROS environment must be set.

Bests
